package emoji

type Emoji struct {
	Emoji string
	Description string
}

var Emojis []Emoji = []Emoji{
	{Emoji: "😀", Description: "grinning face"},
	{Emoji: "😃", Description: "grinning face with big eyes"},
	{Emoji: "😄", Description: "grinning face with smiling eyes"},
	{Emoji: "😁", Description: "beaming face with smiling eyes"},
	{Emoji: "😆", Description: "grinning squinting face"},
	{Emoji: "😅", Description: "grinning face with sweat"},
	{Emoji: "🤣", Description: "rolling on the floor laughing"},
	{Emoji: "😂", Description: "face with tears of joy"},
	{Emoji: "🙂", Description: "slightly smiling face"},
	{Emoji: "🙃", Description: "upside-down face"},
	{Emoji: "🫠", Description: "melting face"},
	{Emoji: "😉", Description: "winking face"},
	{Emoji: "😊", Description: "smiling face with smiling eyes"},
	{Emoji: "😇", Description: "smiling face with halo"},
	{Emoji: "🥰", Description: "smiling face with hearts"},
	{Emoji: "😍", Description: "smiling face with heart-eyes"},
	{Emoji: "🤩", Description: "star-struck"},
	{Emoji: "😘", Description: "face blowing a kiss"},
	{Emoji: "😗", Description: "kissing face"},
	{Emoji: "☺️", Description: "smiling face"},
	{Emoji: "😚", Description: "kissing face with closed eyes"},
	{Emoji: "😙", Description: "kissing face with smiling eyes"},
	{Emoji: "🥲", Description: "smiling face with tear"},
	{Emoji: "😋", Description: "face savoring food"},
	{Emoji: "😛", Description: "face with tongue"},
	{Emoji: "😜", Description: "winking face with tongue"},
	{Emoji: "🤪", Description: "zany face"},
	{Emoji: "😝", Description: "squinting face with tongue"},
	{Emoji: "🤑", Description: "money-mouth face"},
	{Emoji: "🤗", Description: "smiling face with open hands"},
	{Emoji: "🤭", Description: "face with hand over mouth"},
	{Emoji: "🫢", Description: "face with open eyes and hand over mouth"},
	{Emoji: "🫣", Description: "face with peeking eye"},
	{Emoji: "🤫", Description: "shushing face"},
	{Emoji: "🤔", Description: "thinking face"},
	{Emoji: "🫡", Description: "saluting face"},
	{Emoji: "🤐", Description: "zipper-mouth face"},
	{Emoji: "🤨", Description: "face with raised eyebrow"},
	{Emoji: "😐", Description: "neutral face"},
	{Emoji: "😑", Description: "expressionless face"},
	{Emoji: "😶", Description: "face without mouth"},
	{Emoji: "🫥", Description: "dotted line face"},
	{Emoji: "😶‍🌫️", Description: "face in clouds"},
	{Emoji: "😏", Description: "smirking face"},
	{Emoji: "😒", Description: "unamused face"},
	{Emoji: "🙄", Description: "face with rolling eyes"},
	{Emoji: "😬", Description: "grimacing face"},
	{Emoji: "😮‍💨", Description: "face exhaling"},
	{Emoji: "🤥", Description: "lying face"},
	{Emoji: "🫨", Description: "shaking face"},
	{Emoji: "😌", Description: "relieved face"},
	{Emoji: "😔", Description: "pensive face"},
	{Emoji: "😪", Description: "sleepy face"},
	{Emoji: "🤤", Description: "drooling face"},
	{Emoji: "😴", Description: "sleeping face"},
	{Emoji: "😷", Description: "face with medical mask"},
	{Emoji: "🤒", Description: "face with thermometer"},
	{Emoji: "🤕", Description: "face with head-bandage"},
	{Emoji: "🤢", Description: "nauseated face"},
	{Emoji: "🤮", Description: "face vomiting"},
	{Emoji: "🤧", Description: "sneezing face"},
	{Emoji: "🥵", Description: "hot face"},
	{Emoji: "🥶", Description: "cold face"},
	{Emoji: "🥴", Description: "woozy face"},
	{Emoji: "😵", Description: "face with crossed-out eyes"},
	{Emoji: "😵‍💫", Description: "face with spiral eyes"},
	{Emoji: "🤯", Description: "exploding head"},
	{Emoji: "🤠", Description: "cowboy hat face"},
	{Emoji: "🥳", Description: "partying face"},
	{Emoji: "🥸", Description: "disguised face"},
	{Emoji: "😎", Description: "smiling face with sunglasses"},
	{Emoji: "🤓", Description: "nerd face"},
	{Emoji: "🧐", Description: "face with monocle"},
	{Emoji: "😕", Description: "confused face"},
	{Emoji: "🫤", Description: "face with diagonal mouth"},
	{Emoji: "😟", Description: "worried face"},
	{Emoji: "🙁", Description: "slightly frowning face"},
	{Emoji: "☹️", Description: "frowning face"},
	{Emoji: "😮", Description: "face with open mouth"},
	{Emoji: "😯", Description: "hushed face"},
	{Emoji: "😲", Description: "astonished face"},
	{Emoji: "😳", Description: "flushed face"},
	{Emoji: "🥺", Description: "pleading face"},
	{Emoji: "🥹", Description: "face holding back tears"},
	{Emoji: "😦", Description: "frowning face with open mouth"},
	{Emoji: "😧", Description: "anguished face"},
	{Emoji: "😨", Description: "fearful face"},
	{Emoji: "😰", Description: "anxious face with sweat"},
	{Emoji: "😥", Description: "sad but relieved face"},
	{Emoji: "😢", Description: "crying face"},
	{Emoji: "😭", Description: "loudly crying face"},
	{Emoji: "😱", Description: "face screaming in fear"},
	{Emoji: "😖", Description: "confounded face"},
	{Emoji: "😣", Description: "persevering face"},
	{Emoji: "😞", Description: "disappointed face"},
	{Emoji: "😓", Description: "downcast face with sweat"},
	{Emoji: "😩", Description: "weary face"},
	{Emoji: "😫", Description: "tired face"},
	{Emoji: "🥱", Description: "yawning face"},
	{Emoji: "😤", Description: "face with steam from nose"},
	{Emoji: "😡", Description: "enraged face"},
	{Emoji: "😠", Description: "angry face"},
	{Emoji: "🤬", Description: "face with symbols on mouth"},
	{Emoji: "😈", Description: "smiling face with horns"},
	{Emoji: "👿", Description: "angry face with horns"},
	{Emoji: "💀", Description: "skull"},
	{Emoji: "☠️", Description: "skull and crossbones"},
	{Emoji: "💩", Description: "pile of poo"},
	{Emoji: "🤡", Description: "clown face"},
	{Emoji: "👹", Description: "ogre"},
	{Emoji: "👺", Description: "goblin"},
	{Emoji: "👻", Description: "ghost"},
	{Emoji: "👽", Description: "alien"},
	{Emoji: "👾", Description: "alien monster"},
	{Emoji: "🤖", Description: "robot"},
	{Emoji: "😺", Description: "grinning cat"},
	{Emoji: "😸", Description: "grinning cat with smiling eyes"},
	{Emoji: "😹", Description: "cat with tears of joy"},
	{Emoji: "😻", Description: "smiling cat with heart-eyes"},
	{Emoji: "😼", Description: "cat with wry smile"},
	{Emoji: "😽", Description: "kissing cat"},
	{Emoji: "🙀", Description: "weary cat"},
	{Emoji: "😿", Description: "crying cat"},
	{Emoji: "😾", Description: "pouting cat"},
	{Emoji: "🙈", Description: "see-no-evil monkey"},
	{Emoji: "🙉", Description: "hear-no-evil monkey"},
	{Emoji: "🙊", Description: "speak-no-evil monkey"},
	{Emoji: "💌", Description: "love letter"},
	{Emoji: "💘", Description: "heart with arrow"},
	{Emoji: "💝", Description: "heart with ribbon"},
	{Emoji: "💖", Description: "sparkling heart"},
	{Emoji: "💗", Description: "growing heart"},
	{Emoji: "💓", Description: "beating heart"},
	{Emoji: "💞", Description: "revolving hearts"},
	{Emoji: "💕", Description: "two hearts"},
	{Emoji: "💟", Description: "heart decoration"},
	{Emoji: "❣️", Description: "heart exclamation"},
	{Emoji: "💔", Description: "broken heart"},
	{Emoji: "❤️‍🔥", Description: "heart on fire"},
	{Emoji: "❤️‍🩹", Description: "mending heart"},
	{Emoji: "❤️", Description: "red heart"},
	{Emoji: "🩷", Description: "pink heart"},
	{Emoji: "🧡", Description: "orange heart"},
	{Emoji: "💛", Description: "yellow heart"},
	{Emoji: "💚", Description: "green heart"},
	{Emoji: "💙", Description: "blue heart"},
	{Emoji: "🩵", Description: "light blue heart"},
	{Emoji: "💜", Description: "purple heart"},
	{Emoji: "🤎", Description: "brown heart"},
	{Emoji: "🖤", Description: "black heart"},
	{Emoji: "🩶", Description: "grey heart"},
	{Emoji: "🤍", Description: "white heart"},
	{Emoji: "💋", Description: "kiss mark"},
	{Emoji: "💯", Description: "hundred points"},
	{Emoji: "💢", Description: "anger symbol"},
	{Emoji: "💥", Description: "collision"},
	{Emoji: "💫", Description: "dizzy"},
	{Emoji: "💦", Description: "sweat droplets"},
	{Emoji: "💨", Description: "dashing away"},
	{Emoji: "🕳️", Description: "hole"},
	{Emoji: "💬", Description: "speech balloon"},
	{Emoji: "👁️‍🗨️", Description: "eye in speech bubble"},
	{Emoji: "🗨️", Description: "left speech bubble"},
	{Emoji: "🗯️", Description: "right anger bubble"},
	{Emoji: "💭", Description: "thought balloon"},
	{Emoji: "💤", Description: "ZZZ"},
	{Emoji: "👋", Description: "waving hand"},
	{Emoji: "🤚", Description: "raised back of hand"},
	{Emoji: "🖐️", Description: "hand with fingers splayed"},
	{Emoji: "✋", Description: "raised hand"},
	{Emoji: "🖖", Description: "vulcan salute"},
	{Emoji: "🫱", Description: "rightwards hand"},
	{Emoji: "🫲", Description: "leftwards hand"},
	{Emoji: "🫳", Description: "palm down hand"},
	{Emoji: "🫴", Description: "palm up hand"},
	{Emoji: "🫷", Description: "leftwards pushing hand"},
	{Emoji: "🫸", Description: "rightwards pushing hand"},
	{Emoji: "👌", Description: "OK hand"},
	{Emoji: "🤌", Description: "pinched fingers"},
	{Emoji: "🤏", Description: "pinching hand"},
	{Emoji: "✌️", Description: "victory hand"},
	{Emoji: "🤞", Description: "crossed fingers"},
	{Emoji: "🫰", Description: "hand with index finger and thumb crossed"},
	{Emoji: "🤟", Description: "love-you gesture"},
	{Emoji: "🤘", Description: "sign of the horns"},
	{Emoji: "🤙", Description: "call me hand"},
	{Emoji: "👈", Description: "backhand index pointing left"},
	{Emoji: "👉", Description: "backhand index pointing right"},
	{Emoji: "👆", Description: "backhand index pointing up"},
	{Emoji: "🖕", Description: "middle finger"},
	{Emoji: "👇", Description: "backhand index pointing down"},
	{Emoji: "☝️", Description: "index pointing up"},
	{Emoji: "🫵", Description: "index pointing at the viewer"},
	{Emoji: "👍", Description: "thumbs up"},
	{Emoji: "👎", Description: "thumbs down"},
	{Emoji: "✊", Description: "raised fist"},
	{Emoji: "👊", Description: "oncoming fist"},
	{Emoji: "🤛", Description: "left-facing fist"},
	{Emoji: "🤜", Description: "right-facing fist"},
	{Emoji: "👏", Description: "clapping hands"},
	{Emoji: "🙌", Description: "raising hands"},
	{Emoji: "🫶", Description: "heart hands"},
	{Emoji: "👐", Description: "open hands"},
	{Emoji: "🤲", Description: "palms up together"},
	{Emoji: "🤝", Description: "handshake"},
	{Emoji: "🙏", Description: "folded hands"},
	{Emoji: "✍️", Description: "writing hand"},
	{Emoji: "💅", Description: "nail polish"},
	{Emoji: "🤳", Description: "selfie"},
	{Emoji: "💪", Description: "flexed biceps"},
	{Emoji: "🦾", Description: "mechanical arm"},
	{Emoji: "🦿", Description: "mechanical leg"},
	{Emoji: "🦵", Description: "leg"},
	{Emoji: "🦶", Description: "foot"},
	{Emoji: "👂", Description: "ear"},
	{Emoji: "🦻", Description: "ear with hearing aid"},
	{Emoji: "👃", Description: "nose"},
	{Emoji: "🧠", Description: "brain"},
	{Emoji: "🫀", Description: "anatomical heart"},
	{Emoji: "🫁", Description: "lungs"},
	{Emoji: "🦷", Description: "tooth"},
	{Emoji: "🦴", Description: "bone"},
	{Emoji: "👀", Description: "eyes"},
	{Emoji: "👁️", Description: "eye"},
	{Emoji: "👅", Description: "tongue"},
	{Emoji: "👄", Description: "mouth"},
	{Emoji: "🫦", Description: "biting lip"},
	{Emoji: "👶", Description: "baby"},
	{Emoji: "🧒", Description: "child"},
	{Emoji: "👦", Description: "boy"},
	{Emoji: "👧", Description: "girl"},
	{Emoji: "🧑", Description: "person"},
	{Emoji: "👱", Description: "person: blond hair"},
	{Emoji: "👨", Description: "man"},
	{Emoji: "🧔", Description: "person: beard"},
	{Emoji: "🧔‍♂️", Description: "man: beard"},
	{Emoji: "🧔‍♀️", Description: "woman: beard"},
	{Emoji: "👨‍🦰", Description: "man: red hair"},
	{Emoji: "👨‍🦱", Description: "man: curly hair"},
	{Emoji: "👨‍🦳", Description: "man: white hair"},
	{Emoji: "👨‍🦲", Description: "man: bald"},
	{Emoji: "👩", Description: "woman"},
	{Emoji: "👩‍🦰", Description: "woman: red hair"},
	{Emoji: "🧑‍🦰", Description: "person: red hair"},
	{Emoji: "👩‍🦱", Description: "woman: curly hair"},
	{Emoji: "🧑‍🦱", Description: "person: curly hair"},
	{Emoji: "👩‍🦳", Description: "woman: white hair"},
	{Emoji: "🧑‍🦳", Description: "person: white hair"},
	{Emoji: "👩‍🦲", Description: "woman: bald"},
	{Emoji: "🧑‍🦲", Description: "person: bald"},
	{Emoji: "👱‍♀️", Description: "woman: blond hair"},
	{Emoji: "👱‍♂️", Description: "man: blond hair"},
	{Emoji: "🧓", Description: "older person"},
	{Emoji: "👴", Description: "old man"},
	{Emoji: "👵", Description: "old woman"},
	{Emoji: "🙍", Description: "person frowning"},
	{Emoji: "🙍‍♂️", Description: "man frowning"},
	{Emoji: "🙍‍♀️", Description: "woman frowning"},
	{Emoji: "🙎", Description: "person pouting"},
	{Emoji: "🙎‍♂️", Description: "man pouting"},
	{Emoji: "🙎‍♀️", Description: "woman pouting"},
	{Emoji: "🙅", Description: "person gesturing NO"},
	{Emoji: "🙅‍♂️", Description: "man gesturing NO"},
	{Emoji: "🙅‍♀️", Description: "woman gesturing NO"},
	{Emoji: "🙆", Description: "person gesturing OK"},
	{Emoji: "🙆‍♂️", Description: "man gesturing OK"},
	{Emoji: "🙆‍♀️", Description: "woman gesturing OK"},
	{Emoji: "💁", Description: "person tipping hand"},
	{Emoji: "💁‍♂️", Description: "man tipping hand"},
	{Emoji: "💁‍♀️", Description: "woman tipping hand"},
	{Emoji: "🙋", Description: "person raising hand"},
	{Emoji: "🙋‍♂️", Description: "man raising hand"},
	{Emoji: "🙋‍♀️", Description: "woman raising hand"},
	{Emoji: "🧏", Description: "deaf person"},
	{Emoji: "🧏‍♂️", Description: "deaf man"},
	{Emoji: "🧏‍♀️", Description: "deaf woman"},
	{Emoji: "🙇", Description: "person bowing"},
	{Emoji: "🙇‍♂️", Description: "man bowing"},
	{Emoji: "🙇‍♀️", Description: "woman bowing"},
	{Emoji: "🤦", Description: "person facepalming"},
	{Emoji: "🤦‍♂️", Description: "man facepalming"},
	{Emoji: "🤦‍♀️", Description: "woman facepalming"},
	{Emoji: "🤷", Description: "person shrugging"},
	{Emoji: "🤷‍♂️", Description: "man shrugging"},
	{Emoji: "🤷‍♀️", Description: "woman shrugging"},
	{Emoji: "🧑‍⚕️", Description: "health worker"},
	{Emoji: "👨‍⚕️", Description: "man health worker"},
	{Emoji: "👩‍⚕️", Description: "woman health worker"},
	{Emoji: "🧑‍🎓", Description: "student"},
	{Emoji: "👨‍🎓", Description: "man student"},
	{Emoji: "👩‍🎓", Description: "woman student"},
	{Emoji: "🧑‍🏫", Description: "teacher"},
	{Emoji: "👨‍🏫", Description: "man teacher"},
	{Emoji: "👩‍🏫", Description: "woman teacher"},
	{Emoji: "🧑‍⚖️", Description: "judge"},
	{Emoji: "👨‍⚖️", Description: "man judge"},
	{Emoji: "👩‍⚖️", Description: "woman judge"},
	{Emoji: "🧑‍🌾", Description: "farmer"},
	{Emoji: "👨‍🌾", Description: "man farmer"},
	{Emoji: "👩‍🌾", Description: "woman farmer"},
	{Emoji: "🧑‍🍳", Description: "cook"},
	{Emoji: "👨‍🍳", Description: "man cook"},
	{Emoji: "👩‍🍳", Description: "woman cook"},
	{Emoji: "🧑‍🔧", Description: "mechanic"},
	{Emoji: "👨‍🔧", Description: "man mechanic"},
	{Emoji: "👩‍🔧", Description: "woman mechanic"},
	{Emoji: "🧑‍🏭", Description: "factory worker"},
	{Emoji: "👨‍🏭", Description: "man factory worker"},
	{Emoji: "👩‍🏭", Description: "woman factory worker"},
	{Emoji: "🧑‍💼", Description: "office worker"},
	{Emoji: "👨‍💼", Description: "man office worker"},
	{Emoji: "👩‍💼", Description: "woman office worker"},
	{Emoji: "🧑‍🔬", Description: "scientist"},
	{Emoji: "👨‍🔬", Description: "man scientist"},
	{Emoji: "👩‍🔬", Description: "woman scientist"},
	{Emoji: "🧑‍💻", Description: "technologist"},
	{Emoji: "👨‍💻", Description: "man technologist"},
	{Emoji: "👩‍💻", Description: "woman technologist"},
	{Emoji: "🧑‍🎤", Description: "singer"},
	{Emoji: "👨‍🎤", Description: "man singer"},
	{Emoji: "👩‍🎤", Description: "woman singer"},
	{Emoji: "🧑‍🎨", Description: "artist"},
	{Emoji: "👨‍🎨", Description: "man artist"},
	{Emoji: "👩‍🎨", Description: "woman artist"},
	{Emoji: "🧑‍✈️", Description: "pilot"},
	{Emoji: "👨‍✈️", Description: "man pilot"},
	{Emoji: "👩‍✈️", Description: "woman pilot"},
	{Emoji: "🧑‍🚀", Description: "astronaut"},
	{Emoji: "👨‍🚀", Description: "man astronaut"},
	{Emoji: "👩‍🚀", Description: "woman astronaut"},
	{Emoji: "🧑‍🚒", Description: "firefighter"},
	{Emoji: "👨‍🚒", Description: "man firefighter"},
	{Emoji: "👩‍🚒", Description: "woman firefighter"},
	{Emoji: "👮", Description: "police officer"},
	{Emoji: "👮‍♂️", Description: "man police officer"},
	{Emoji: "👮‍♀️", Description: "woman police officer"},
	{Emoji: "🕵️", Description: "detective"},
	{Emoji: "🕵️‍♂️", Description: "man detective"},
	{Emoji: "🕵️‍♀️", Description: "woman detective"},
	{Emoji: "💂", Description: "guard"},
	{Emoji: "💂‍♂️", Description: "man guard"},
	{Emoji: "💂‍♀️", Description: "woman guard"},
	{Emoji: "🥷", Description: "ninja"},
	{Emoji: "👷", Description: "construction worker"},
	{Emoji: "👷‍♂️", Description: "man construction worker"},
	{Emoji: "👷‍♀️", Description: "woman construction worker"},
	{Emoji: "🫅", Description: "person with crown"},
	{Emoji: "🤴", Description: "prince"},
	{Emoji: "👸", Description: "princess"},
	{Emoji: "👳", Description: "person wearing turban"},
	{Emoji: "👳‍♂️", Description: "man wearing turban"},
	{Emoji: "👳‍♀️", Description: "woman wearing turban"},
	{Emoji: "👲", Description: "person with skullcap"},
	{Emoji: "🧕", Description: "woman with headscarf"},
	{Emoji: "🤵", Description: "person in tuxedo"},
	{Emoji: "🤵‍♂️", Description: "man in tuxedo"},
	{Emoji: "🤵‍♀️", Description: "woman in tuxedo"},
	{Emoji: "👰", Description: "person with veil"},
	{Emoji: "👰‍♂️", Description: "man with veil"},
	{Emoji: "👰‍♀️", Description: "woman with veil"},
	{Emoji: "🤰", Description: "pregnant woman"},
	{Emoji: "🫃", Description: "pregnant man"},
	{Emoji: "🫄", Description: "pregnant person"},
	{Emoji: "🤱", Description: "breast-feeding"},
	{Emoji: "👩‍🍼", Description: "woman feeding baby"},
	{Emoji: "👨‍🍼", Description: "man feeding baby"},
	{Emoji: "🧑‍🍼", Description: "person feeding baby"},
	{Emoji: "👼", Description: "baby angel"},
	{Emoji: "🎅", Description: "Santa Claus"},
	{Emoji: "🤶", Description: "Mrs. Claus"},
	{Emoji: "🧑‍🎄", Description: "mx claus"},
	{Emoji: "🦸", Description: "superhero"},
	{Emoji: "🦸‍♂️", Description: "man superhero"},
	{Emoji: "🦸‍♀️", Description: "woman superhero"},
	{Emoji: "🦹", Description: "supervillain"},
	{Emoji: "🦹‍♂️", Description: "man supervillain"},
	{Emoji: "🦹‍♀️", Description: "woman supervillain"},
	{Emoji: "🧙", Description: "mage"},
	{Emoji: "🧙‍♂️", Description: "man mage"},
	{Emoji: "🧙‍♀️", Description: "woman mage"},
	{Emoji: "🧚", Description: "fairy"},
	{Emoji: "🧚‍♂️", Description: "man fairy"},
	{Emoji: "🧚‍♀️", Description: "woman fairy"},
	{Emoji: "🧛", Description: "vampire"},
	{Emoji: "🧛‍♂️", Description: "man vampire"},
	{Emoji: "🧛‍♀️", Description: "woman vampire"},
	{Emoji: "🧜", Description: "merperson"},
	{Emoji: "🧜‍♂️", Description: "merman"},
	{Emoji: "🧜‍♀️", Description: "mermaid"},
	{Emoji: "🧝", Description: "elf"},
	{Emoji: "🧝‍♂️", Description: "man elf"},
	{Emoji: "🧝‍♀️", Description: "woman elf"},
	{Emoji: "🧞", Description: "genie"},
	{Emoji: "🧞‍♂️", Description: "man genie"},
	{Emoji: "🧞‍♀️", Description: "woman genie"},
	{Emoji: "🧟", Description: "zombie"},
	{Emoji: "🧟‍♂️", Description: "man zombie"},
	{Emoji: "🧟‍♀️", Description: "woman zombie"},
	{Emoji: "🧌", Description: "troll"},
	{Emoji: "💆", Description: "person getting massage"},
	{Emoji: "💆‍♂️", Description: "man getting massage"},
	{Emoji: "💆‍♀️", Description: "woman getting massage"},
	{Emoji: "💇", Description: "person getting haircut"},
	{Emoji: "💇‍♂️", Description: "man getting haircut"},
	{Emoji: "💇‍♀️", Description: "woman getting haircut"},
	{Emoji: "🚶", Description: "person walking"},
	{Emoji: "🚶‍♂️", Description: "man walking"},
	{Emoji: "🚶‍♀️", Description: "woman walking"},
	{Emoji: "🧍", Description: "person standing"},
	{Emoji: "🧍‍♂️", Description: "man standing"},
	{Emoji: "🧍‍♀️", Description: "woman standing"},
	{Emoji: "🧎", Description: "person kneeling"},
	{Emoji: "🧎‍♂️", Description: "man kneeling"},
	{Emoji: "🧎‍♀️", Description: "woman kneeling"},
	{Emoji: "🧑‍🦯", Description: "person with white cane"},
	{Emoji: "👨‍🦯", Description: "man with white cane"},
	{Emoji: "👩‍🦯", Description: "woman with white cane"},
	{Emoji: "🧑‍🦼", Description: "person in motorized wheelchair"},
	{Emoji: "👨‍🦼", Description: "man in motorized wheelchair"},
	{Emoji: "👩‍🦼", Description: "woman in motorized wheelchair"},
	{Emoji: "🧑‍🦽", Description: "person in manual wheelchair"},
	{Emoji: "👨‍🦽", Description: "man in manual wheelchair"},
	{Emoji: "👩‍🦽", Description: "woman in manual wheelchair"},
	{Emoji: "🏃", Description: "person running"},
	{Emoji: "🏃‍♂️", Description: "man running"},
	{Emoji: "🏃‍♀️", Description: "woman running"},
	{Emoji: "💃", Description: "woman dancing"},
	{Emoji: "🕺", Description: "man dancing"},
	{Emoji: "🕴️", Description: "person in suit levitating"},
	{Emoji: "👯", Description: "people with bunny ears"},
	{Emoji: "👯‍♂️", Description: "men with bunny ears"},
	{Emoji: "👯‍♀️", Description: "women with bunny ears"},
	{Emoji: "🧖", Description: "person in steamy room"},
	{Emoji: "🧖‍♂️", Description: "man in steamy room"},
	{Emoji: "🧖‍♀️", Description: "woman in steamy room"},
	{Emoji: "🧗", Description: "person climbing"},
	{Emoji: "🧗‍♂️", Description: "man climbing"},
	{Emoji: "🧗‍♀️", Description: "woman climbing"},
	{Emoji: "🤺", Description: "person fencing"},
	{Emoji: "🏇", Description: "horse racing"},
	{Emoji: "⛷️", Description: "skier"},
	{Emoji: "🏂", Description: "snowboarder"},
	{Emoji: "🏌️", Description: "person golfing"},
	{Emoji: "🏌️‍♂️", Description: "man golfing"},
	{Emoji: "🏌️‍♀️", Description: "woman golfing"},
	{Emoji: "🏄", Description: "person surfing"},
	{Emoji: "🏄‍♂️", Description: "man surfing"},
	{Emoji: "🏄‍♀️", Description: "woman surfing"},
	{Emoji: "🚣", Description: "person rowing boat"},
	{Emoji: "🚣‍♂️", Description: "man rowing boat"},
	{Emoji: "🚣‍♀️", Description: "woman rowing boat"},
	{Emoji: "🏊", Description: "person swimming"},
	{Emoji: "🏊‍♂️", Description: "man swimming"},
	{Emoji: "🏊‍♀️", Description: "woman swimming"},
	{Emoji: "⛹️", Description: "person bouncing ball"},
	{Emoji: "⛹️‍♂️", Description: "man bouncing ball"},
	{Emoji: "⛹️‍♀️", Description: "woman bouncing ball"},
	{Emoji: "🏋️", Description: "person lifting weights"},
	{Emoji: "🏋️‍♂️", Description: "man lifting weights"},
	{Emoji: "🏋️‍♀️", Description: "woman lifting weights"},
	{Emoji: "🚴", Description: "person biking"},
	{Emoji: "🚴‍♂️", Description: "man biking"},
	{Emoji: "🚴‍♀️", Description: "woman biking"},
	{Emoji: "🚵", Description: "person mountain biking"},
	{Emoji: "🚵‍♂️", Description: "man mountain biking"},
	{Emoji: "🚵‍♀️", Description: "woman mountain biking"},
	{Emoji: "🤸", Description: "person cartwheeling"},
	{Emoji: "🤸‍♂️", Description: "man cartwheeling"},
	{Emoji: "🤸‍♀️", Description: "woman cartwheeling"},
	{Emoji: "🤼", Description: "people wrestling"},
	{Emoji: "🤼‍♂️", Description: "men wrestling"},
	{Emoji: "🤼‍♀️", Description: "women wrestling"},
	{Emoji: "🤽", Description: "person playing water polo"},
	{Emoji: "🤽‍♂️", Description: "man playing water polo"},
	{Emoji: "🤽‍♀️", Description: "woman playing water polo"},
	{Emoji: "🤾", Description: "person playing handball"},
	{Emoji: "🤾‍♂️", Description: "man playing handball"},
	{Emoji: "🤾‍♀️", Description: "woman playing handball"},
	{Emoji: "🤹", Description: "person juggling"},
	{Emoji: "🤹‍♂️", Description: "man juggling"},
	{Emoji: "🤹‍♀️", Description: "woman juggling"},
	{Emoji: "🧘", Description: "person in lotus position"},
	{Emoji: "🧘‍♂️", Description: "man in lotus position"},
	{Emoji: "🧘‍♀️", Description: "woman in lotus position"},
	{Emoji: "🛀", Description: "person taking bath"},
	{Emoji: "🛌", Description: "person in bed"},
	{Emoji: "🧑‍🤝‍🧑", Description: "people holding hands"},
	{Emoji: "👭", Description: "women holding hands"},
	{Emoji: "👫", Description: "woman and man holding hands"},
	{Emoji: "👬", Description: "men holding hands"},
	{Emoji: "💏", Description: "kiss"},
	{Emoji: "👩‍❤️‍💋‍👨", Description: "kiss: woman, man"},
	{Emoji: "👨‍❤️‍💋‍👨", Description: "kiss: man, man"},
	{Emoji: "👩‍❤️‍💋‍👩", Description: "kiss: woman, woman"},
	{Emoji: "💑", Description: "couple with heart"},
	{Emoji: "👩‍❤️‍👨", Description: "couple with heart: woman, man"},
	{Emoji: "👨‍❤️‍👨", Description: "couple with heart: man, man"},
	{Emoji: "👩‍❤️‍👩", Description: "couple with heart: woman, woman"},
	{Emoji: "👪", Description: "family"},
	{Emoji: "👨‍👩‍👦", Description: "family: man, woman, boy"},
	{Emoji: "👨‍👩‍👧", Description: "family: man, woman, girl"},
	{Emoji: "👨‍👩‍👧‍👦", Description: "family: man, woman, girl, boy"},
	{Emoji: "👨‍👩‍👦‍👦", Description: "family: man, woman, boy, boy"},
	{Emoji: "👨‍👩‍👧‍👧", Description: "family: man, woman, girl, girl"},
	{Emoji: "👨‍👨‍👦", Description: "family: man, man, boy"},
	{Emoji: "👨‍👨‍👧", Description: "family: man, man, girl"},
	{Emoji: "👨‍👨‍👧‍👦", Description: "family: man, man, girl, boy"},
	{Emoji: "👨‍👨‍👦‍👦", Description: "family: man, man, boy, boy"},
	{Emoji: "👨‍👨‍👧‍👧", Description: "family: man, man, girl, girl"},
	{Emoji: "👩‍👩‍👦", Description: "family: woman, woman, boy"},
	{Emoji: "👩‍👩‍👧", Description: "family: woman, woman, girl"},
	{Emoji: "👩‍👩‍👧‍👦", Description: "family: woman, woman, girl, boy"},
	{Emoji: "👩‍👩‍👦‍👦", Description: "family: woman, woman, boy, boy"},
	{Emoji: "👩‍👩‍👧‍👧", Description: "family: woman, woman, girl, girl"},
	{Emoji: "👨‍👦", Description: "family: man, boy"},
	{Emoji: "👨‍👦‍👦", Description: "family: man, boy, boy"},
	{Emoji: "👨‍👧", Description: "family: man, girl"},
	{Emoji: "👨‍👧‍👦", Description: "family: man, girl, boy"},
	{Emoji: "👨‍👧‍👧", Description: "family: man, girl, girl"},
	{Emoji: "👩‍👦", Description: "family: woman, boy"},
	{Emoji: "👩‍👦‍👦", Description: "family: woman, boy, boy"},
	{Emoji: "👩‍👧", Description: "family: woman, girl"},
	{Emoji: "👩‍👧‍👦", Description: "family: woman, girl, boy"},
	{Emoji: "👩‍👧‍👧", Description: "family: woman, girl, girl"},
	{Emoji: "🗣️", Description: "speaking head"},
	{Emoji: "👤", Description: "bust in silhouette"},
	{Emoji: "👥", Description: "busts in silhouette"},
	{Emoji: "🫂", Description: "people hugging"},
	{Emoji: "👣", Description: "footprints"},
	{Emoji: "🐵", Description: "monkey face"},
	{Emoji: "🐒", Description: "monkey"},
	{Emoji: "🦍", Description: "gorilla"},
	{Emoji: "🦧", Description: "orangutan"},
	{Emoji: "🐶", Description: "dog face"},
	{Emoji: "🐕", Description: "dog"},
	{Emoji: "🦮", Description: "guide dog"},
	{Emoji: "🐕‍🦺", Description: "service dog"},
	{Emoji: "🐩", Description: "poodle"},
	{Emoji: "🐺", Description: "wolf"},
	{Emoji: "🦊", Description: "fox"},
	{Emoji: "🦝", Description: "raccoon"},
	{Emoji: "🐱", Description: "cat face"},
	{Emoji: "🐈", Description: "cat"},
	{Emoji: "🐈‍⬛", Description: "black cat"},
	{Emoji: "🦁", Description: "lion"},
	{Emoji: "🐯", Description: "tiger face"},
	{Emoji: "🐅", Description: "tiger"},
	{Emoji: "🐆", Description: "leopard"},
	{Emoji: "🐴", Description: "horse face"},
	{Emoji: "🫎", Description: "moose"},
	{Emoji: "🫏", Description: "donkey"},
	{Emoji: "🐎", Description: "horse"},
	{Emoji: "🦄", Description: "unicorn"},
	{Emoji: "🦓", Description: "zebra"},
	{Emoji: "🦌", Description: "deer"},
	{Emoji: "🦬", Description: "bison"},
	{Emoji: "🐮", Description: "cow face"},
	{Emoji: "🐂", Description: "ox"},
	{Emoji: "🐃", Description: "water buffalo"},
	{Emoji: "🐄", Description: "cow"},
	{Emoji: "🐷", Description: "pig face"},
	{Emoji: "🐖", Description: "pig"},
	{Emoji: "🐗", Description: "boar"},
	{Emoji: "🐽", Description: "pig nose"},
	{Emoji: "🐏", Description: "ram"},
	{Emoji: "🐑", Description: "ewe"},
	{Emoji: "🐐", Description: "goat"},
	{Emoji: "🐪", Description: "camel"},
	{Emoji: "🐫", Description: "two-hump camel"},
	{Emoji: "🦙", Description: "llama"},
	{Emoji: "🦒", Description: "giraffe"},
	{Emoji: "🐘", Description: "elephant"},
	{Emoji: "🦣", Description: "mammoth"},
	{Emoji: "🦏", Description: "rhinoceros"},
	{Emoji: "🦛", Description: "hippopotamus"},
	{Emoji: "🐭", Description: "mouse face"},
	{Emoji: "🐁", Description: "mouse"},
	{Emoji: "🐀", Description: "rat"},
	{Emoji: "🐹", Description: "hamster"},
	{Emoji: "🐰", Description: "rabbit face"},
	{Emoji: "🐇", Description: "rabbit"},
	{Emoji: "🐿️", Description: "chipmunk"},
	{Emoji: "🦫", Description: "beaver"},
	{Emoji: "🦔", Description: "hedgehog"},
	{Emoji: "🦇", Description: "bat"},
	{Emoji: "🐻", Description: "bear"},
	{Emoji: "🐻‍❄️", Description: "polar bear"},
	{Emoji: "🐨", Description: "koala"},
	{Emoji: "🐼", Description: "panda"},
	{Emoji: "🦥", Description: "sloth"},
	{Emoji: "🦦", Description: "otter"},
	{Emoji: "🦨", Description: "skunk"},
	{Emoji: "🦘", Description: "kangaroo"},
	{Emoji: "🦡", Description: "badger"},
	{Emoji: "🐾", Description: "paw prints"},
	{Emoji: "🦃", Description: "turkey"},
	{Emoji: "🐔", Description: "chicken"},
	{Emoji: "🐓", Description: "rooster"},
	{Emoji: "🐣", Description: "hatching chick"},
	{Emoji: "🐤", Description: "baby chick"},
	{Emoji: "🐥", Description: "front-facing baby chick"},
	{Emoji: "🐦", Description: "bird"},
	{Emoji: "🐧", Description: "penguin"},
	{Emoji: "🕊️", Description: "dove"},
	{Emoji: "🦅", Description: "eagle"},
	{Emoji: "🦆", Description: "duck"},
	{Emoji: "🦢", Description: "swan"},
	{Emoji: "🦉", Description: "owl"},
	{Emoji: "🦤", Description: "dodo"},
	{Emoji: "🪶", Description: "feather"},
	{Emoji: "🦩", Description: "flamingo"},
	{Emoji: "🦚", Description: "peacock"},
	{Emoji: "🦜", Description: "parrot"},
	{Emoji: "🪽", Description: "wing"},
	{Emoji: "🐦‍⬛", Description: "black bird"},
	{Emoji: "🪿", Description: "goose"},
	{Emoji: "🐸", Description: "frog"},
	{Emoji: "🐊", Description: "crocodile"},
	{Emoji: "🐢", Description: "turtle"},
	{Emoji: "🦎", Description: "lizard"},
	{Emoji: "🐍", Description: "snake"},
	{Emoji: "🐲", Description: "dragon face"},
	{Emoji: "🐉", Description: "dragon"},
	{Emoji: "🦕", Description: "sauropod"},
	{Emoji: "🦖", Description: "T-Rex"},
	{Emoji: "🐳", Description: "spouting whale"},
	{Emoji: "🐋", Description: "whale"},
	{Emoji: "🐬", Description: "dolphin"},
	{Emoji: "🦭", Description: "seal"},
	{Emoji: "🐟", Description: "fish"},
	{Emoji: "🐠", Description: "tropical fish"},
	{Emoji: "🐡", Description: "blowfish"},
	{Emoji: "🦈", Description: "shark"},
	{Emoji: "🐙", Description: "octopus"},
	{Emoji: "🐚", Description: "spiral shell"},
	{Emoji: "🪸", Description: "coral"},
	{Emoji: "🪼", Description: "jellyfish"},
	{Emoji: "🐌", Description: "snail"},
	{Emoji: "🦋", Description: "butterfly"},
	{Emoji: "🐛", Description: "bug"},
	{Emoji: "🐜", Description: "ant"},
	{Emoji: "🐝", Description: "honeybee"},
	{Emoji: "🪲", Description: "beetle"},
	{Emoji: "🐞", Description: "lady beetle"},
	{Emoji: "🦗", Description: "cricket"},
	{Emoji: "🪳", Description: "cockroach"},
	{Emoji: "🕷️", Description: "spider"},
	{Emoji: "🕸️", Description: "spider web"},
	{Emoji: "🦂", Description: "scorpion"},
	{Emoji: "🦟", Description: "mosquito"},
	{Emoji: "🪰", Description: "fly"},
	{Emoji: "🪱", Description: "worm"},
	{Emoji: "🦠", Description: "microbe"},
	{Emoji: "💐", Description: "bouquet"},
	{Emoji: "🌸", Description: "cherry blossom"},
	{Emoji: "💮", Description: "white flower"},
	{Emoji: "🪷", Description: "lotus"},
	{Emoji: "🏵️", Description: "rosette"},
	{Emoji: "🌹", Description: "rose"},
	{Emoji: "🥀", Description: "wilted flower"},
	{Emoji: "🌺", Description: "hibiscus"},
	{Emoji: "🌻", Description: "sunflower"},
	{Emoji: "🌼", Description: "blossom"},
	{Emoji: "🌷", Description: "tulip"},
	{Emoji: "🪻", Description: "hyacinth"},
	{Emoji: "🌱", Description: "seedling"},
	{Emoji: "🪴", Description: "potted plant"},
	{Emoji: "🌲", Description: "evergreen tree"},
	{Emoji: "🌳", Description: "deciduous tree"},
	{Emoji: "🌴", Description: "palm tree"},
	{Emoji: "🌵", Description: "cactus"},
	{Emoji: "🌾", Description: "sheaf of rice"},
	{Emoji: "🌿", Description: "herb"},
	{Emoji: "☘️", Description: "shamrock"},
	{Emoji: "🍀", Description: "four leaf clover"},
	{Emoji: "🍁", Description: "maple leaf"},
	{Emoji: "🍂", Description: "fallen leaf"},
	{Emoji: "🍃", Description: "leaf fluttering in wind"},
	{Emoji: "🪹", Description: "empty nest"},
	{Emoji: "🪺", Description: "nest with eggs"},
	{Emoji: "🍄", Description: "mushroom"},
	{Emoji: "🍇", Description: "grapes"},
	{Emoji: "🍈", Description: "melon"},
	{Emoji: "🍉", Description: "watermelon"},
	{Emoji: "🍊", Description: "tangerine"},
	{Emoji: "🍋", Description: "lemon"},
	{Emoji: "🍌", Description: "banana"},
	{Emoji: "🍍", Description: "pineapple"},
	{Emoji: "🥭", Description: "mango"},
	{Emoji: "🍎", Description: "red apple"},
	{Emoji: "🍏", Description: "green apple"},
	{Emoji: "🍐", Description: "pear"},
	{Emoji: "🍑", Description: "peach"},
	{Emoji: "🍒", Description: "cherries"},
	{Emoji: "🍓", Description: "strawberry"},
	{Emoji: "🫐", Description: "blueberries"},
	{Emoji: "🥝", Description: "kiwi fruit"},
	{Emoji: "🍅", Description: "tomato"},
	{Emoji: "🫒", Description: "olive"},
	{Emoji: "🥥", Description: "coconut"},
	{Emoji: "🥑", Description: "avocado"},
	{Emoji: "🍆", Description: "eggplant"},
	{Emoji: "🥔", Description: "potato"},
	{Emoji: "🥕", Description: "carrot"},
	{Emoji: "🌽", Description: "ear of corn"},
	{Emoji: "🌶️", Description: "hot pepper"},
	{Emoji: "🫑", Description: "bell pepper"},
	{Emoji: "🥒", Description: "cucumber"},
	{Emoji: "🥬", Description: "leafy green"},
	{Emoji: "🥦", Description: "broccoli"},
	{Emoji: "🧄", Description: "garlic"},
	{Emoji: "🧅", Description: "onion"},
	{Emoji: "🥜", Description: "peanuts"},
	{Emoji: "🫘", Description: "beans"},
	{Emoji: "🌰", Description: "chestnut"},
	{Emoji: "🫚", Description: "ginger root"},
	{Emoji: "🫛", Description: "pea pod"},
	{Emoji: "🍞", Description: "bread"},
	{Emoji: "🥐", Description: "croissant"},
	{Emoji: "🥖", Description: "baguette bread"},
	{Emoji: "🫓", Description: "flatbread"},
	{Emoji: "🥨", Description: "pretzel"},
	{Emoji: "🥯", Description: "bagel"},
	{Emoji: "🥞", Description: "pancakes"},
	{Emoji: "🧇", Description: "waffle"},
	{Emoji: "🧀", Description: "cheese wedge"},
	{Emoji: "🍖", Description: "meat on bone"},
	{Emoji: "🍗", Description: "poultry leg"},
	{Emoji: "🥩", Description: "cut of meat"},
	{Emoji: "🥓", Description: "bacon"},
	{Emoji: "🍔", Description: "hamburger"},
	{Emoji: "🍟", Description: "french fries"},
	{Emoji: "🍕", Description: "pizza"},
	{Emoji: "🌭", Description: "hot dog"},
	{Emoji: "🥪", Description: "sandwich"},
	{Emoji: "🌮", Description: "taco"},
	{Emoji: "🌯", Description: "burrito"},
	{Emoji: "🫔", Description: "tamale"},
	{Emoji: "🥙", Description: "stuffed flatbread"},
	{Emoji: "🧆", Description: "falafel"},
	{Emoji: "🥚", Description: "egg"},
	{Emoji: "🍳", Description: "cooking"},
	{Emoji: "🥘", Description: "shallow pan of food"},
	{Emoji: "🍲", Description: "pot of food"},
	{Emoji: "🫕", Description: "fondue"},
	{Emoji: "🥣", Description: "bowl with spoon"},
	{Emoji: "🥗", Description: "green salad"},
	{Emoji: "🍿", Description: "popcorn"},
	{Emoji: "🧈", Description: "butter"},
	{Emoji: "🧂", Description: "salt"},
	{Emoji: "🥫", Description: "canned food"},
	{Emoji: "🍱", Description: "bento box"},
	{Emoji: "🍘", Description: "rice cracker"},
	{Emoji: "🍙", Description: "rice ball"},
	{Emoji: "🍚", Description: "cooked rice"},
	{Emoji: "🍛", Description: "curry rice"},
	{Emoji: "🍜", Description: "steaming bowl"},
	{Emoji: "🍝", Description: "spaghetti"},
	{Emoji: "🍠", Description: "roasted sweet potato"},
	{Emoji: "🍢", Description: "oden"},
	{Emoji: "🍣", Description: "sushi"},
	{Emoji: "🍤", Description: "fried shrimp"},
	{Emoji: "🍥", Description: "fish cake with swirl"},
	{Emoji: "🥮", Description: "moon cake"},
	{Emoji: "🍡", Description: "dango"},
	{Emoji: "🥟", Description: "dumpling"},
	{Emoji: "🥠", Description: "fortune cookie"},
	{Emoji: "🥡", Description: "takeout box"},
	{Emoji: "🦀", Description: "crab"},
	{Emoji: "🦞", Description: "lobster"},
	{Emoji: "🦐", Description: "shrimp"},
	{Emoji: "🦑", Description: "squid"},
	{Emoji: "🦪", Description: "oyster"},
	{Emoji: "🍦", Description: "soft ice cream"},
	{Emoji: "🍧", Description: "shaved ice"},
	{Emoji: "🍨", Description: "ice cream"},
	{Emoji: "🍩", Description: "doughnut"},
	{Emoji: "🍪", Description: "cookie"},
	{Emoji: "🎂", Description: "birthday cake"},
	{Emoji: "🍰", Description: "shortcake"},
	{Emoji: "🧁", Description: "cupcake"},
	{Emoji: "🥧", Description: "pie"},
	{Emoji: "🍫", Description: "chocolate bar"},
	{Emoji: "🍬", Description: "candy"},
	{Emoji: "🍭", Description: "lollipop"},
	{Emoji: "🍮", Description: "custard"},
	{Emoji: "🍯", Description: "honey pot"},
	{Emoji: "🍼", Description: "baby bottle"},
	{Emoji: "🥛", Description: "glass of milk"},
	{Emoji: "☕", Description: "hot beverage"},
	{Emoji: "🫖", Description: "teapot"},
	{Emoji: "🍵", Description: "teacup without handle"},
	{Emoji: "🍶", Description: "sake"},
	{Emoji: "🍾", Description: "bottle with popping cork"},
	{Emoji: "🍷", Description: "wine glass"},
	{Emoji: "🍸", Description: "cocktail glass"},
	{Emoji: "🍹", Description: "tropical drink"},
	{Emoji: "🍺", Description: "beer mug"},
	{Emoji: "🍻", Description: "clinking beer mugs"},
	{Emoji: "🥂", Description: "clinking glasses"},
	{Emoji: "🥃", Description: "tumbler glass"},
	{Emoji: "🫗", Description: "pouring liquid"},
	{Emoji: "🥤", Description: "cup with straw"},
	{Emoji: "🧋", Description: "bubble tea"},
	{Emoji: "🧃", Description: "beverage box"},
	{Emoji: "🧉", Description: "mate"},
	{Emoji: "🧊", Description: "ice"},
	{Emoji: "🥢", Description: "chopsticks"},
	{Emoji: "🍽️", Description: "fork and knife with plate"},
	{Emoji: "🍴", Description: "fork and knife"},
	{Emoji: "🥄", Description: "spoon"},
	{Emoji: "🔪", Description: "kitchen knife"},
	{Emoji: "🫙", Description: "jar"},
	{Emoji: "🏺", Description: "amphora"},
	{Emoji: "🌍", Description: "globe showing Europe-Africa"},
	{Emoji: "🌎", Description: "globe showing Americas"},
	{Emoji: "🌏", Description: "globe showing Asia-Australia"},
	{Emoji: "🌐", Description: "globe with meridians"},
	{Emoji: "🗺️", Description: "world map"},
	{Emoji: "🗾", Description: "map of Japan"},
	{Emoji: "🧭", Description: "compass"},
	{Emoji: "🏔️", Description: "snow-capped mountain"},
	{Emoji: "⛰️", Description: "mountain"},
	{Emoji: "🌋", Description: "volcano"},
	{Emoji: "🗻", Description: "mount fuji"},
	{Emoji: "🏕️", Description: "camping"},
	{Emoji: "🏖️", Description: "beach with umbrella"},
	{Emoji: "🏜️", Description: "desert"},
	{Emoji: "🏝️", Description: "desert island"},
	{Emoji: "🏞️", Description: "national park"},
	{Emoji: "🏟️", Description: "stadium"},
	{Emoji: "🏛️", Description: "classical building"},
	{Emoji: "🏗️", Description: "building construction"},
	{Emoji: "🧱", Description: "brick"},
	{Emoji: "🪨", Description: "rock"},
	{Emoji: "🪵", Description: "wood"},
	{Emoji: "🛖", Description: "hut"},
	{Emoji: "🏘️", Description: "houses"},
	{Emoji: "🏚️", Description: "derelict house"},
	{Emoji: "🏠", Description: "house"},
	{Emoji: "🏡", Description: "house with garden"},
	{Emoji: "🏢", Description: "office building"},
	{Emoji: "🏣", Description: "Japanese post office"},
	{Emoji: "🏤", Description: "post office"},
	{Emoji: "🏥", Description: "hospital"},
	{Emoji: "🏦", Description: "bank"},
	{Emoji: "🏨", Description: "hotel"},
	{Emoji: "🏩", Description: "love hotel"},
	{Emoji: "🏪", Description: "convenience store"},
	{Emoji: "🏫", Description: "school"},
	{Emoji: "🏬", Description: "department store"},
	{Emoji: "🏭", Description: "factory"},
	{Emoji: "🏯", Description: "Japanese castle"},
	{Emoji: "🏰", Description: "castle"},
	{Emoji: "💒", Description: "wedding"},
	{Emoji: "🗼", Description: "Tokyo tower"},
	{Emoji: "🗽", Description: "Statue of Liberty"},
	{Emoji: "⛪", Description: "church"},
	{Emoji: "🕌", Description: "mosque"},
	{Emoji: "🛕", Description: "hindu temple"},
	{Emoji: "🕍", Description: "synagogue"},
	{Emoji: "⛩️", Description: "shinto shrine"},
	{Emoji: "🕋", Description: "kaaba"},
	{Emoji: "⛲", Description: "fountain"},
	{Emoji: "⛺", Description: "tent"},
	{Emoji: "🌁", Description: "foggy"},
	{Emoji: "🌃", Description: "night with stars"},
	{Emoji: "🏙️", Description: "cityscape"},
	{Emoji: "🌄", Description: "sunrise over mountains"},
	{Emoji: "🌅", Description: "sunrise"},
	{Emoji: "🌆", Description: "cityscape at dusk"},
	{Emoji: "🌇", Description: "sunset"},
	{Emoji: "🌉", Description: "bridge at night"},
	{Emoji: "♨️", Description: "hot springs"},
	{Emoji: "🎠", Description: "carousel horse"},
	{Emoji: "🛝", Description: "playground slide"},
	{Emoji: "🎡", Description: "ferris wheel"},
	{Emoji: "🎢", Description: "roller coaster"},
	{Emoji: "💈", Description: "barber pole"},
	{Emoji: "🎪", Description: "circus tent"},
	{Emoji: "🚂", Description: "locomotive"},
	{Emoji: "🚃", Description: "railway car"},
	{Emoji: "🚄", Description: "high-speed train"},
	{Emoji: "🚅", Description: "bullet train"},
	{Emoji: "🚆", Description: "train"},
	{Emoji: "🚇", Description: "metro"},
	{Emoji: "🚈", Description: "light rail"},
	{Emoji: "🚉", Description: "station"},
	{Emoji: "🚊", Description: "tram"},
	{Emoji: "🚝", Description: "monorail"},
	{Emoji: "🚞", Description: "mountain railway"},
	{Emoji: "🚋", Description: "tram car"},
	{Emoji: "🚌", Description: "bus"},
	{Emoji: "🚍", Description: "oncoming bus"},
	{Emoji: "🚎", Description: "trolleybus"},
	{Emoji: "🚐", Description: "minibus"},
	{Emoji: "🚑", Description: "ambulance"},
	{Emoji: "🚒", Description: "fire engine"},
	{Emoji: "🚓", Description: "police car"},
	{Emoji: "🚔", Description: "oncoming police car"},
	{Emoji: "🚕", Description: "taxi"},
	{Emoji: "🚖", Description: "oncoming taxi"},
	{Emoji: "🚗", Description: "automobile"},
	{Emoji: "🚘", Description: "oncoming automobile"},
	{Emoji: "🚙", Description: "sport utility vehicle"},
	{Emoji: "🛻", Description: "pickup truck"},
	{Emoji: "🚚", Description: "delivery truck"},
	{Emoji: "🚛", Description: "articulated lorry"},
	{Emoji: "🚜", Description: "tractor"},
	{Emoji: "🏎️", Description: "racing car"},
	{Emoji: "🏍️", Description: "motorcycle"},
	{Emoji: "🛵", Description: "motor scooter"},
	{Emoji: "🦽", Description: "manual wheelchair"},
	{Emoji: "🦼", Description: "motorized wheelchair"},
	{Emoji: "🛺", Description: "auto rickshaw"},
	{Emoji: "🚲", Description: "bicycle"},
	{Emoji: "🛴", Description: "kick scooter"},
	{Emoji: "🛹", Description: "skateboard"},
	{Emoji: "🛼", Description: "roller skate"},
	{Emoji: "🚏", Description: "bus stop"},
	{Emoji: "🛣️", Description: "motorway"},
	{Emoji: "🛤️", Description: "railway track"},
	{Emoji: "🛢️", Description: "oil drum"},
	{Emoji: "⛽", Description: "fuel pump"},
	{Emoji: "🛞", Description: "wheel"},
	{Emoji: "🚨", Description: "police car light"},
	{Emoji: "🚥", Description: "horizontal traffic light"},
	{Emoji: "🚦", Description: "vertical traffic light"},
	{Emoji: "🛑", Description: "stop sign"},
	{Emoji: "🚧", Description: "construction"},
	{Emoji: "⚓", Description: "anchor"},
	{Emoji: "🛟", Description: "ring buoy"},
	{Emoji: "⛵", Description: "sailboat"},
	{Emoji: "🛶", Description: "canoe"},
	{Emoji: "🚤", Description: "speedboat"},
	{Emoji: "🛳️", Description: "passenger ship"},
	{Emoji: "⛴️", Description: "ferry"},
	{Emoji: "🛥️", Description: "motor boat"},
	{Emoji: "🚢", Description: "ship"},
	{Emoji: "✈️", Description: "airplane"},
	{Emoji: "🛩️", Description: "small airplane"},
	{Emoji: "🛫", Description: "airplane departure"},
	{Emoji: "🛬", Description: "airplane arrival"},
	{Emoji: "🪂", Description: "parachute"},
	{Emoji: "💺", Description: "seat"},
	{Emoji: "🚁", Description: "helicopter"},
	{Emoji: "🚟", Description: "suspension railway"},
	{Emoji: "🚠", Description: "mountain cableway"},
	{Emoji: "🚡", Description: "aerial tramway"},
	{Emoji: "🛰️", Description: "satellite"},
	{Emoji: "🚀", Description: "rocket"},
	{Emoji: "🛸", Description: "flying saucer"},
	{Emoji: "🛎️", Description: "bellhop bell"},
	{Emoji: "🧳", Description: "luggage"},
	{Emoji: "⌛", Description: "hourglass done"},
	{Emoji: "⏳", Description: "hourglass not done"},
	{Emoji: "⌚", Description: "watch"},
	{Emoji: "⏰", Description: "alarm clock"},
	{Emoji: "⏱️", Description: "stopwatch"},
	{Emoji: "⏲️", Description: "timer clock"},
	{Emoji: "🕰️", Description: "mantelpiece clock"},
	{Emoji: "🕛", Description: "twelve o’clock"},
	{Emoji: "🕧", Description: "twelve-thirty"},
	{Emoji: "🕐", Description: "one o’clock"},
	{Emoji: "🕜", Description: "one-thirty"},
	{Emoji: "🕑", Description: "two o’clock"},
	{Emoji: "🕝", Description: "two-thirty"},
	{Emoji: "🕒", Description: "three o’clock"},
	{Emoji: "🕞", Description: "three-thirty"},
	{Emoji: "🕓", Description: "four o’clock"},
	{Emoji: "🕟", Description: "four-thirty"},
	{Emoji: "🕔", Description: "five o’clock"},
	{Emoji: "🕠", Description: "five-thirty"},
	{Emoji: "🕕", Description: "six o’clock"},
	{Emoji: "🕡", Description: "six-thirty"},
	{Emoji: "🕖", Description: "seven o’clock"},
	{Emoji: "🕢", Description: "seven-thirty"},
	{Emoji: "🕗", Description: "eight o’clock"},
	{Emoji: "🕣", Description: "eight-thirty"},
	{Emoji: "🕘", Description: "nine o’clock"},
	{Emoji: "🕤", Description: "nine-thirty"},
	{Emoji: "🕙", Description: "ten o’clock"},
	{Emoji: "🕥", Description: "ten-thirty"},
	{Emoji: "🕚", Description: "eleven o’clock"},
	{Emoji: "🕦", Description: "eleven-thirty"},
	{Emoji: "🌑", Description: "new moon"},
	{Emoji: "🌒", Description: "waxing crescent moon"},
	{Emoji: "🌓", Description: "first quarter moon"},
	{Emoji: "🌔", Description: "waxing gibbous moon"},
	{Emoji: "🌕", Description: "full moon"},
	{Emoji: "🌖", Description: "waning gibbous moon"},
	{Emoji: "🌗", Description: "last quarter moon"},
	{Emoji: "🌘", Description: "waning crescent moon"},
	{Emoji: "🌙", Description: "crescent moon"},
	{Emoji: "🌚", Description: "new moon face"},
	{Emoji: "🌛", Description: "first quarter moon face"},
	{Emoji: "🌜", Description: "last quarter moon face"},
	{Emoji: "🌡️", Description: "thermometer"},
	{Emoji: "☀️", Description: "sun"},
	{Emoji: "🌝", Description: "full moon face"},
	{Emoji: "🌞", Description: "sun with face"},
	{Emoji: "🪐", Description: "ringed planet"},
	{Emoji: "⭐", Description: "star"},
	{Emoji: "🌟", Description: "glowing star"},
	{Emoji: "🌠", Description: "shooting star"},
	{Emoji: "🌌", Description: "milky way"},
	{Emoji: "☁️", Description: "cloud"},
	{Emoji: "⛅", Description: "sun behind cloud"},
	{Emoji: "⛈️", Description: "cloud with lightning and rain"},
	{Emoji: "🌤️", Description: "sun behind small cloud"},
	{Emoji: "🌥️", Description: "sun behind large cloud"},
	{Emoji: "🌦️", Description: "sun behind rain cloud"},
	{Emoji: "🌧️", Description: "cloud with rain"},
	{Emoji: "🌨️", Description: "cloud with snow"},
	{Emoji: "🌩️", Description: "cloud with lightning"},
	{Emoji: "🌪️", Description: "tornado"},
	{Emoji: "🌫️", Description: "fog"},
	{Emoji: "🌬️", Description: "wind face"},
	{Emoji: "🌀", Description: "cyclone"},
	{Emoji: "🌈", Description: "rainbow"},
	{Emoji: "🌂", Description: "closed umbrella"},
	{Emoji: "☂️", Description: "umbrella"},
	{Emoji: "☔", Description: "umbrella with rain drops"},
	{Emoji: "⛱️", Description: "umbrella on ground"},
	{Emoji: "⚡", Description: "high voltage"},
	{Emoji: "❄️", Description: "snowflake"},
	{Emoji: "☃️", Description: "snowman"},
	{Emoji: "⛄", Description: "snowman without snow"},
	{Emoji: "☄️", Description: "comet"},
	{Emoji: "🔥", Description: "fire"},
	{Emoji: "💧", Description: "droplet"},
	{Emoji: "🌊", Description: "water wave"},
	{Emoji: "🎃", Description: "jack-o-lantern"},
	{Emoji: "🎄", Description: "Christmas tree"},
	{Emoji: "🎆", Description: "fireworks"},
	{Emoji: "🎇", Description: "sparkler"},
	{Emoji: "🧨", Description: "firecracker"},
	{Emoji: "✨", Description: "sparkles"},
	{Emoji: "🎈", Description: "balloon"},
	{Emoji: "🎉", Description: "party popper"},
	{Emoji: "🎊", Description: "confetti ball"},
	{Emoji: "🎋", Description: "tanabata tree"},
	{Emoji: "🎍", Description: "pine decoration"},
	{Emoji: "🎎", Description: "Japanese dolls"},
	{Emoji: "🎏", Description: "carp streamer"},
	{Emoji: "🎐", Description: "wind chime"},
	{Emoji: "🎑", Description: "moon viewing ceremony"},
	{Emoji: "🧧", Description: "red envelope"},
	{Emoji: "🎀", Description: "ribbon"},
	{Emoji: "🎁", Description: "wrapped gift"},
	{Emoji: "🎗️", Description: "reminder ribbon"},
	{Emoji: "🎟️", Description: "admission tickets"},
	{Emoji: "🎫", Description: "ticket"},
	{Emoji: "🎖️", Description: "military medal"},
	{Emoji: "🏆", Description: "trophy"},
	{Emoji: "🏅", Description: "sports medal"},
	{Emoji: "🥇", Description: "1st place medal"},
	{Emoji: "🥈", Description: "2nd place medal"},
	{Emoji: "🥉", Description: "3rd place medal"},
	{Emoji: "⚽", Description: "soccer ball"},
	{Emoji: "⚾", Description: "baseball"},
	{Emoji: "🥎", Description: "softball"},
	{Emoji: "🏀", Description: "basketball"},
	{Emoji: "🏐", Description: "volleyball"},
	{Emoji: "🏈", Description: "american football"},
	{Emoji: "🏉", Description: "rugby football"},
	{Emoji: "🎾", Description: "tennis"},
	{Emoji: "🥏", Description: "flying disc"},
	{Emoji: "🎳", Description: "bowling"},
	{Emoji: "🏏", Description: "cricket game"},
	{Emoji: "🏑", Description: "field hockey"},
	{Emoji: "🏒", Description: "ice hockey"},
	{Emoji: "🥍", Description: "lacrosse"},
	{Emoji: "🏓", Description: "ping pong"},
	{Emoji: "🏸", Description: "badminton"},
	{Emoji: "🥊", Description: "boxing glove"},
	{Emoji: "🥋", Description: "martial arts uniform"},
	{Emoji: "🥅", Description: "goal net"},
	{Emoji: "⛳", Description: "flag in hole"},
	{Emoji: "⛸️", Description: "ice skate"},
	{Emoji: "🎣", Description: "fishing pole"},
	{Emoji: "🤿", Description: "diving mask"},
	{Emoji: "🎽", Description: "running shirt"},
	{Emoji: "🎿", Description: "skis"},
	{Emoji: "🛷", Description: "sled"},
	{Emoji: "🥌", Description: "curling stone"},
	{Emoji: "🎯", Description: "bullseye"},
	{Emoji: "🪀", Description: "yo-yo"},
	{Emoji: "🪁", Description: "kite"},
	{Emoji: "🔫", Description: "water pistol"},
	{Emoji: "🎱", Description: "pool 8 ball"},
	{Emoji: "🔮", Description: "crystal ball"},
	{Emoji: "🪄", Description: "magic wand"},
	{Emoji: "🎮", Description: "video game"},
	{Emoji: "🕹️", Description: "joystick"},
	{Emoji: "🎰", Description: "slot machine"},
	{Emoji: "🎲", Description: "game die"},
	{Emoji: "🧩", Description: "puzzle piece"},
	{Emoji: "🧸", Description: "teddy bear"},
	{Emoji: "🪅", Description: "piñata"},
	{Emoji: "🪩", Description: "mirror ball"},
	{Emoji: "🪆", Description: "nesting dolls"},
	{Emoji: "♠️", Description: "spade suit"},
	{Emoji: "♥️", Description: "heart suit"},
	{Emoji: "♦️", Description: "diamond suit"},
	{Emoji: "♣️", Description: "club suit"},
	{Emoji: "♟️", Description: "chess pawn"},
	{Emoji: "🃏", Description: "joker"},
	{Emoji: "🀄", Description: "mahjong red dragon"},
	{Emoji: "🎴", Description: "flower playing cards"},
	{Emoji: "🎭", Description: "performing arts"},
	{Emoji: "🖼️", Description: "framed picture"},
	{Emoji: "🎨", Description: "artist palette"},
	{Emoji: "🧵", Description: "thread"},
	{Emoji: "🪡", Description: "sewing needle"},
	{Emoji: "🧶", Description: "yarn"},
	{Emoji: "🪢", Description: "knot"},
	{Emoji: "👓", Description: "glasses"},
	{Emoji: "🕶️", Description: "sunglasses"},
	{Emoji: "🥽", Description: "goggles"},
	{Emoji: "🥼", Description: "lab coat"},
	{Emoji: "🦺", Description: "safety vest"},
	{Emoji: "👔", Description: "necktie"},
	{Emoji: "👕", Description: "t-shirt"},
	{Emoji: "👖", Description: "jeans"},
	{Emoji: "🧣", Description: "scarf"},
	{Emoji: "🧤", Description: "gloves"},
	{Emoji: "🧥", Description: "coat"},
	{Emoji: "🧦", Description: "socks"},
	{Emoji: "👗", Description: "dress"},
	{Emoji: "👘", Description: "kimono"},
	{Emoji: "🥻", Description: "sari"},
	{Emoji: "🩱", Description: "one-piece swimsuit"},
	{Emoji: "🩲", Description: "briefs"},
	{Emoji: "🩳", Description: "shorts"},
	{Emoji: "👙", Description: "bikini"},
	{Emoji: "👚", Description: "woman’s clothes"},
	{Emoji: "🪭", Description: "folding hand fan"},
	{Emoji: "👛", Description: "purse"},
	{Emoji: "👜", Description: "handbag"},
	{Emoji: "👝", Description: "clutch bag"},
	{Emoji: "🛍️", Description: "shopping bags"},
	{Emoji: "🎒", Description: "backpack"},
	{Emoji: "🩴", Description: "thong sandal"},
	{Emoji: "👞", Description: "man’s shoe"},
	{Emoji: "👟", Description: "running shoe"},
	{Emoji: "🥾", Description: "hiking boot"},
	{Emoji: "🥿", Description: "flat shoe"},
	{Emoji: "👠", Description: "high-heeled shoe"},
	{Emoji: "👡", Description: "woman’s sandal"},
	{Emoji: "🩰", Description: "ballet shoes"},
	{Emoji: "👢", Description: "woman’s boot"},
	{Emoji: "🪮", Description: "hair pick"},
	{Emoji: "👑", Description: "crown"},
	{Emoji: "👒", Description: "woman’s hat"},
	{Emoji: "🎩", Description: "top hat"},
	{Emoji: "🎓", Description: "graduation cap"},
	{Emoji: "🧢", Description: "billed cap"},
	{Emoji: "🪖", Description: "military helmet"},
	{Emoji: "⛑️", Description: "rescue worker’s helmet"},
	{Emoji: "📿", Description: "prayer beads"},
	{Emoji: "💄", Description: "lipstick"},
	{Emoji: "💍", Description: "ring"},
	{Emoji: "💎", Description: "gem stone"},
	{Emoji: "🔇", Description: "muted speaker"},
	{Emoji: "🔈", Description: "speaker low volume"},
	{Emoji: "🔉", Description: "speaker medium volume"},
	{Emoji: "🔊", Description: "speaker high volume"},
	{Emoji: "📢", Description: "loudspeaker"},
	{Emoji: "📣", Description: "megaphone"},
	{Emoji: "📯", Description: "postal horn"},
	{Emoji: "🔔", Description: "bell"},
	{Emoji: "🔕", Description: "bell with slash"},
	{Emoji: "🎼", Description: "musical score"},
	{Emoji: "🎵", Description: "musical note"},
	{Emoji: "🎶", Description: "musical notes"},
	{Emoji: "🎙️", Description: "studio microphone"},
	{Emoji: "🎚️", Description: "level slider"},
	{Emoji: "🎛️", Description: "control knobs"},
	{Emoji: "🎤", Description: "microphone"},
	{Emoji: "🎧", Description: "headphone"},
	{Emoji: "📻", Description: "radio"},
	{Emoji: "🎷", Description: "saxophone"},
	{Emoji: "🪗", Description: "accordion"},
	{Emoji: "🎸", Description: "guitar"},
	{Emoji: "🎹", Description: "musical keyboard"},
	{Emoji: "🎺", Description: "trumpet"},
	{Emoji: "🎻", Description: "violin"},
	{Emoji: "🪕", Description: "banjo"},
	{Emoji: "🥁", Description: "drum"},
	{Emoji: "🪘", Description: "long drum"},
	{Emoji: "🪇", Description: "maracas"},
	{Emoji: "🪈", Description: "flute"},
	{Emoji: "📱", Description: "mobile phone"},
	{Emoji: "📲", Description: "mobile phone with arrow"},
	{Emoji: "☎️", Description: "telephone"},
	{Emoji: "📞", Description: "telephone receiver"},
	{Emoji: "📟", Description: "pager"},
	{Emoji: "📠", Description: "fax machine"},
	{Emoji: "🔋", Description: "battery"},
	{Emoji: "🪫", Description: "low battery"},
	{Emoji: "🔌", Description: "electric plug"},
	{Emoji: "💻", Description: "laptop"},
	{Emoji: "🖥️", Description: "desktop computer"},
	{Emoji: "🖨️", Description: "printer"},
	{Emoji: "⌨️", Description: "keyboard"},
	{Emoji: "🖱️", Description: "computer mouse"},
	{Emoji: "🖲️", Description: "trackball"},
	{Emoji: "💽", Description: "computer disk"},
	{Emoji: "💾", Description: "floppy disk"},
	{Emoji: "💿", Description: "optical disk"},
	{Emoji: "📀", Description: "dvd"},
	{Emoji: "🧮", Description: "abacus"},
	{Emoji: "🎥", Description: "movie camera"},
	{Emoji: "🎞️", Description: "film frames"},
	{Emoji: "📽️", Description: "film projector"},
	{Emoji: "🎬", Description: "clapper board"},
	{Emoji: "📺", Description: "television"},
	{Emoji: "📷", Description: "camera"},
	{Emoji: "📸", Description: "camera with flash"},
	{Emoji: "📹", Description: "video camera"},
	{Emoji: "📼", Description: "videocassette"},
	{Emoji: "🔍", Description: "magnifying glass tilted left"},
	{Emoji: "🔎", Description: "magnifying glass tilted right"},
	{Emoji: "🕯️", Description: "candle"},
	{Emoji: "💡", Description: "light bulb"},
	{Emoji: "🔦", Description: "flashlight"},
	{Emoji: "🏮", Description: "red paper lantern"},
	{Emoji: "🪔", Description: "diya lamp"},
	{Emoji: "📔", Description: "notebook with decorative cover"},
	{Emoji: "📕", Description: "closed book"},
	{Emoji: "📖", Description: "open book"},
	{Emoji: "📗", Description: "green book"},
	{Emoji: "📘", Description: "blue book"},
	{Emoji: "📙", Description: "orange book"},
	{Emoji: "📚", Description: "books"},
	{Emoji: "📓", Description: "notebook"},
	{Emoji: "📒", Description: "ledger"},
	{Emoji: "📃", Description: "page with curl"},
	{Emoji: "📜", Description: "scroll"},
	{Emoji: "📄", Description: "page facing up"},
	{Emoji: "📰", Description: "newspaper"},
	{Emoji: "🗞️", Description: "rolled-up newspaper"},
	{Emoji: "📑", Description: "bookmark tabs"},
	{Emoji: "🔖", Description: "bookmark"},
	{Emoji: "🏷️", Description: "label"},
	{Emoji: "💰", Description: "money bag"},
	{Emoji: "🪙", Description: "coin"},
	{Emoji: "💴", Description: "yen banknote"},
	{Emoji: "💵", Description: "dollar banknote"},
	{Emoji: "💶", Description: "euro banknote"},
	{Emoji: "💷", Description: "pound banknote"},
	{Emoji: "💸", Description: "money with wings"},
	{Emoji: "💳", Description: "credit card"},
	{Emoji: "🧾", Description: "receipt"},
	{Emoji: "💹", Description: "chart increasing with yen"},
	{Emoji: "✉️", Description: "envelope"},
	{Emoji: "📧", Description: "e-mail"},
	{Emoji: "📨", Description: "incoming envelope"},
	{Emoji: "📩", Description: "envelope with arrow"},
	{Emoji: "📤", Description: "outbox tray"},
	{Emoji: "📥", Description: "inbox tray"},
	{Emoji: "📦", Description: "package"},
	{Emoji: "📫", Description: "closed mailbox with raised flag"},
	{Emoji: "📪", Description: "closed mailbox with lowered flag"},
	{Emoji: "📬", Description: "open mailbox with raised flag"},
	{Emoji: "📭", Description: "open mailbox with lowered flag"},
	{Emoji: "📮", Description: "postbox"},
	{Emoji: "🗳️", Description: "ballot box with ballot"},
	{Emoji: "✏️", Description: "pencil"},
	{Emoji: "✒️", Description: "black nib"},
	{Emoji: "🖋️", Description: "fountain pen"},
	{Emoji: "🖊️", Description: "pen"},
	{Emoji: "🖌️", Description: "paintbrush"},
	{Emoji: "🖍️", Description: "crayon"},
	{Emoji: "📝", Description: "memo"},
	{Emoji: "💼", Description: "briefcase"},
	{Emoji: "📁", Description: "file folder"},
	{Emoji: "📂", Description: "open file folder"},
	{Emoji: "🗂️", Description: "card index dividers"},
	{Emoji: "📅", Description: "calendar"},
	{Emoji: "📆", Description: "tear-off calendar"},
	{Emoji: "🗒️", Description: "spiral notepad"},
	{Emoji: "🗓️", Description: "spiral calendar"},
	{Emoji: "📇", Description: "card index"},
	{Emoji: "📈", Description: "chart increasing"},
	{Emoji: "📉", Description: "chart decreasing"},
	{Emoji: "📊", Description: "bar chart"},
	{Emoji: "📋", Description: "clipboard"},
	{Emoji: "📌", Description: "pushpin"},
	{Emoji: "📍", Description: "round pushpin"},
	{Emoji: "📎", Description: "paperclip"},
	{Emoji: "🖇️", Description: "linked paperclips"},
	{Emoji: "📏", Description: "straight ruler"},
	{Emoji: "📐", Description: "triangular ruler"},
	{Emoji: "✂️", Description: "scissors"},
	{Emoji: "🗃️", Description: "card file box"},
	{Emoji: "🗄️", Description: "file cabinet"},
	{Emoji: "🗑️", Description: "wastebasket"},
	{Emoji: "🔒", Description: "locked"},
	{Emoji: "🔓", Description: "unlocked"},
	{Emoji: "🔏", Description: "locked with pen"},
	{Emoji: "🔐", Description: "locked with key"},
	{Emoji: "🔑", Description: "key"},
	{Emoji: "🗝️", Description: "old key"},
	{Emoji: "🔨", Description: "hammer"},
	{Emoji: "🪓", Description: "axe"},
	{Emoji: "⛏️", Description: "pick"},
	{Emoji: "⚒️", Description: "hammer and pick"},
	{Emoji: "🛠️", Description: "hammer and wrench"},
	{Emoji: "🗡️", Description: "dagger"},
	{Emoji: "⚔️", Description: "crossed swords"},
	{Emoji: "💣", Description: "bomb"},
	{Emoji: "🪃", Description: "boomerang"},
	{Emoji: "🏹", Description: "bow and arrow"},
	{Emoji: "🛡️", Description: "shield"},
	{Emoji: "🪚", Description: "carpentry saw"},
	{Emoji: "🔧", Description: "wrench"},
	{Emoji: "🪛", Description: "screwdriver"},
	{Emoji: "🔩", Description: "nut and bolt"},
	{Emoji: "⚙️", Description: "gear"},
	{Emoji: "🗜️", Description: "clamp"},
	{Emoji: "⚖️", Description: "balance scale"},
	{Emoji: "🦯", Description: "white cane"},
	{Emoji: "🔗", Description: "link"},
	{Emoji: "⛓️", Description: "chains"},
	{Emoji: "🪝", Description: "hook"},
	{Emoji: "🧰", Description: "toolbox"},
	{Emoji: "🧲", Description: "magnet"},
	{Emoji: "🪜", Description: "ladder"},
	{Emoji: "⚗️", Description: "alembic"},
	{Emoji: "🧪", Description: "test tube"},
	{Emoji: "🧫", Description: "petri dish"},
	{Emoji: "🧬", Description: "dna"},
	{Emoji: "🔬", Description: "microscope"},
	{Emoji: "🔭", Description: "telescope"},
	{Emoji: "📡", Description: "satellite antenna"},
	{Emoji: "💉", Description: "syringe"},
	{Emoji: "🩸", Description: "drop of blood"},
	{Emoji: "💊", Description: "pill"},
	{Emoji: "🩹", Description: "adhesive bandage"},
	{Emoji: "🩼", Description: "crutch"},
	{Emoji: "🩺", Description: "stethoscope"},
	{Emoji: "🩻", Description: "x-ray"},
	{Emoji: "🚪", Description: "door"},
	{Emoji: "🛗", Description: "elevator"},
	{Emoji: "🪞", Description: "mirror"},
	{Emoji: "🪟", Description: "window"},
	{Emoji: "🛏️", Description: "bed"},
	{Emoji: "🛋️", Description: "couch and lamp"},
	{Emoji: "🪑", Description: "chair"},
	{Emoji: "🚽", Description: "toilet"},
	{Emoji: "🪠", Description: "plunger"},
	{Emoji: "🚿", Description: "shower"},
	{Emoji: "🛁", Description: "bathtub"},
	{Emoji: "🪤", Description: "mouse trap"},
	{Emoji: "🪒", Description: "razor"},
	{Emoji: "🧴", Description: "lotion bottle"},
	{Emoji: "🧷", Description: "safety pin"},
	{Emoji: "🧹", Description: "broom"},
	{Emoji: "🧺", Description: "basket"},
	{Emoji: "🧻", Description: "roll of paper"},
	{Emoji: "🪣", Description: "bucket"},
	{Emoji: "🧼", Description: "soap"},
	{Emoji: "🫧", Description: "bubbles"},
	{Emoji: "🪥", Description: "toothbrush"},
	{Emoji: "🧽", Description: "sponge"},
	{Emoji: "🧯", Description: "fire extinguisher"},
	{Emoji: "🛒", Description: "shopping cart"},
	{Emoji: "🚬", Description: "cigarette"},
	{Emoji: "⚰️", Description: "coffin"},
	{Emoji: "🪦", Description: "headstone"},
	{Emoji: "⚱️", Description: "funeral urn"},
	{Emoji: "🧿", Description: "nazar amulet"},
	{Emoji: "🪬", Description: "hamsa"},
	{Emoji: "🗿", Description: "moai"},
	{Emoji: "🪧", Description: "placard"},
	{Emoji: "🪪", Description: "identification card"},
	{Emoji: "🏧", Description: "ATM sign"},
	{Emoji: "🚮", Description: "litter in bin sign"},
	{Emoji: "🚰", Description: "potable water"},
	{Emoji: "♿", Description: "wheelchair symbol"},
	{Emoji: "🚹", Description: "men’s room"},
	{Emoji: "🚺", Description: "women’s room"},
	{Emoji: "🚻", Description: "restroom"},
	{Emoji: "🚼", Description: "baby symbol"},
	{Emoji: "🚾", Description: "water closet"},
	{Emoji: "🛂", Description: "passport control"},
	{Emoji: "🛃", Description: "customs"},
	{Emoji: "🛄", Description: "baggage claim"},
	{Emoji: "🛅", Description: "left luggage"},
	{Emoji: "⚠️", Description: "warning"},
	{Emoji: "🚸", Description: "children crossing"},
	{Emoji: "⛔", Description: "no entry"},
	{Emoji: "🚫", Description: "prohibited"},
	{Emoji: "🚳", Description: "no bicycles"},
	{Emoji: "🚭", Description: "no smoking"},
	{Emoji: "🚯", Description: "no littering"},
	{Emoji: "🚱", Description: "non-potable water"},
	{Emoji: "🚷", Description: "no pedestrians"},
	{Emoji: "📵", Description: "no mobile phones"},
	{Emoji: "🔞", Description: "no one under eighteen"},
	{Emoji: "☢️", Description: "radioactive"},
	{Emoji: "☣️", Description: "biohazard"},
	{Emoji: "⬆️", Description: "up arrow"},
	{Emoji: "↗️", Description: "up-right arrow"},
	{Emoji: "➡️", Description: "right arrow"},
	{Emoji: "↘️", Description: "down-right arrow"},
	{Emoji: "⬇️", Description: "down arrow"},
	{Emoji: "↙️", Description: "down-left arrow"},
	{Emoji: "⬅️", Description: "left arrow"},
	{Emoji: "↖️", Description: "up-left arrow"},
	{Emoji: "↕️", Description: "up-down arrow"},
	{Emoji: "↔️", Description: "left-right arrow"},
	{Emoji: "↩️", Description: "right arrow curving left"},
	{Emoji: "↪️", Description: "left arrow curving right"},
	{Emoji: "⤴️", Description: "right arrow curving up"},
	{Emoji: "⤵️", Description: "right arrow curving down"},
	{Emoji: "🔃", Description: "clockwise vertical arrows"},
	{Emoji: "🔄", Description: "counterclockwise arrows button"},
	{Emoji: "🔙", Description: "BACK arrow"},
	{Emoji: "🔚", Description: "END arrow"},
	{Emoji: "🔛", Description: "ON! arrow"},
	{Emoji: "🔜", Description: "SOON arrow"},
	{Emoji: "🔝", Description: "TOP arrow"},
	{Emoji: "🛐", Description: "place of worship"},
	{Emoji: "⚛️", Description: "atom symbol"},
	{Emoji: "🕉️", Description: "om"},
	{Emoji: "✡️", Description: "star of David"},
	{Emoji: "☸️", Description: "wheel of dharma"},
	{Emoji: "☯️", Description: "yin yang"},
	{Emoji: "✝️", Description: "latin cross"},
	{Emoji: "☦️", Description: "orthodox cross"},
	{Emoji: "☪️", Description: "star and crescent"},
	{Emoji: "☮️", Description: "peace symbol"},
	{Emoji: "🕎", Description: "menorah"},
	{Emoji: "🔯", Description: "dotted six-pointed star"},
	{Emoji: "🪯", Description: "khanda"},
	{Emoji: "♈", Description: "Aries"},
	{Emoji: "♉", Description: "Taurus"},
	{Emoji: "♊", Description: "Gemini"},
	{Emoji: "♋", Description: "Cancer"},
	{Emoji: "♌", Description: "Leo"},
	{Emoji: "♍", Description: "Virgo"},
	{Emoji: "♎", Description: "Libra"},
	{Emoji: "♏", Description: "Scorpio"},
	{Emoji: "♐", Description: "Sagittarius"},
	{Emoji: "♑", Description: "Capricorn"},
	{Emoji: "♒", Description: "Aquarius"},
	{Emoji: "♓", Description: "Pisces"},
	{Emoji: "⛎", Description: "Ophiuchus"},
	{Emoji: "🔀", Description: "shuffle tracks button"},
	{Emoji: "🔁", Description: "repeat button"},
	{Emoji: "🔂", Description: "repeat single button"},
	{Emoji: "▶️", Description: "play button"},
	{Emoji: "⏩", Description: "fast-forward button"},
	{Emoji: "⏭️", Description: "next track button"},
	{Emoji: "⏯️", Description: "play or pause button"},
	{Emoji: "◀️", Description: "reverse button"},
	{Emoji: "⏪", Description: "fast reverse button"},
	{Emoji: "⏮️", Description: "last track button"},
	{Emoji: "🔼", Description: "upwards button"},
	{Emoji: "⏫", Description: "fast up button"},
	{Emoji: "🔽", Description: "downwards button"},
	{Emoji: "⏬", Description: "fast down button"},
	{Emoji: "⏸️", Description: "pause button"},
	{Emoji: "⏹️", Description: "stop button"},
	{Emoji: "⏺️", Description: "record button"},
	{Emoji: "⏏️", Description: "eject button"},
	{Emoji: "🎦", Description: "cinema"},
	{Emoji: "🔅", Description: "dim button"},
	{Emoji: "🔆", Description: "bright button"},
	{Emoji: "📶", Description: "antenna bars"},
	{Emoji: "🛜", Description: "wireless"},
	{Emoji: "📳", Description: "vibration mode"},
	{Emoji: "📴", Description: "mobile phone off"},
	{Emoji: "♀️", Description: "female sign"},
	{Emoji: "♂️", Description: "male sign"},
	{Emoji: "⚧️", Description: "transgender symbol"},
	{Emoji: "✖️", Description: "multiply"},
	{Emoji: "➕", Description: "plus"},
	{Emoji: "➖", Description: "minus"},
	{Emoji: "➗", Description: "divide"},
	{Emoji: "🟰", Description: "heavy equals sign"},
	{Emoji: "♾️", Description: "infinity"},
	{Emoji: "‼️", Description: "double exclamation mark"},
	{Emoji: "⁉️", Description: "exclamation question mark"},
	{Emoji: "❓", Description: "red question mark"},
	{Emoji: "❔", Description: "white question mark"},
	{Emoji: "❕", Description: "white exclamation mark"},
	{Emoji: "❗", Description: "red exclamation mark"},
	{Emoji: "〰️", Description: "wavy dash"},
	{Emoji: "💱", Description: "currency exchange"},
	{Emoji: "💲", Description: "heavy dollar sign"},
	{Emoji: "⚕️", Description: "medical symbol"},
	{Emoji: "♻️", Description: "recycling symbol"},
	{Emoji: "⚜️", Description: "fleur-de-lis"},
	{Emoji: "🔱", Description: "trident emblem"},
	{Emoji: "📛", Description: "name badge"},
	{Emoji: "🔰", Description: "Japanese symbol for beginner"},
	{Emoji: "⭕", Description: "hollow red circle"},
	{Emoji: "✅", Description: "check mark button"},
	{Emoji: "☑️", Description: "check box with check"},
	{Emoji: "✔️", Description: "check mark"},
	{Emoji: "❌", Description: "cross mark"},
	{Emoji: "❎", Description: "cross mark button"},
	{Emoji: "➰", Description: "curly loop"},
	{Emoji: "➿", Description: "double curly loop"},
	{Emoji: "〽️", Description: "part alternation mark"},
	{Emoji: "✳️", Description: "eight-spoked asterisk"},
	{Emoji: "✴️", Description: "eight-pointed star"},
	{Emoji: "❇️", Description: "sparkle"},
	{Emoji: "©️", Description: "copyright"},
	{Emoji: "®️", Description: "registered"},
	{Emoji: "™️", Description: "trade mark"},
	{Emoji: "#️⃣", Description: "keycap: #"},
	{Emoji: "*️⃣", Description: "keycap: *"},
	{Emoji: "0️⃣", Description: "keycap: 0"},
	{Emoji: "1️⃣", Description: "keycap: 1"},
	{Emoji: "2️⃣", Description: "keycap: 2"},
	{Emoji: "3️⃣", Description: "keycap: 3"},
	{Emoji: "4️⃣", Description: "keycap: 4"},
	{Emoji: "5️⃣", Description: "keycap: 5"},
	{Emoji: "6️⃣", Description: "keycap: 6"},
	{Emoji: "7️⃣", Description: "keycap: 7"},
	{Emoji: "8️⃣", Description: "keycap: 8"},
	{Emoji: "9️⃣", Description: "keycap: 9"},
	{Emoji: "🔟", Description: "keycap: 10"},
	{Emoji: "🔠", Description: "input latin uppercase"},
	{Emoji: "🔡", Description: "input latin lowercase"},
	{Emoji: "🔢", Description: "input numbers"},
	{Emoji: "🔣", Description: "input symbols"},
	{Emoji: "🔤", Description: "input latin letters"},
	{Emoji: "🅰️", Description: "A button (blood type)"},
	{Emoji: "🆎", Description: "AB button (blood type)"},
	{Emoji: "🅱️", Description: "B button (blood type)"},
	{Emoji: "🆑", Description: "CL button"},
	{Emoji: "🆒", Description: "COOL button"},
	{Emoji: "🆓", Description: "FREE button"},
	{Emoji: "ℹ️", Description: "information"},
	{Emoji: "🆔", Description: "ID button"},
	{Emoji: "Ⓜ️", Description: "circled M"},
	{Emoji: "🆕", Description: "NEW button"},
	{Emoji: "🆖", Description: "NG button"},
	{Emoji: "🅾️", Description: "O button (blood type)"},
	{Emoji: "🆗", Description: "OK button"},
	{Emoji: "🅿️", Description: "P button"},
	{Emoji: "🆘", Description: "SOS button"},
	{Emoji: "🆙", Description: "UP! button"},
	{Emoji: "🆚", Description: "VS button"},
	{Emoji: "🈁", Description: "Japanese “here” button"},
	{Emoji: "🈂️", Description: "Japanese “service charge” button"},
	{Emoji: "🈷️", Description: "Japanese “monthly amount” button"},
	{Emoji: "🈶", Description: "Japanese “not free of charge” button"},
	{Emoji: "🈯", Description: "Japanese “reserved” button"},
	{Emoji: "🉐", Description: "Japanese “bargain” button"},
	{Emoji: "🈹", Description: "Japanese “discount” button"},
	{Emoji: "🈚", Description: "Japanese “free of charge” button"},
	{Emoji: "🈲", Description: "Japanese “prohibited” button"},
	{Emoji: "🉑", Description: "Japanese “acceptable” button"},
	{Emoji: "🈸", Description: "Japanese “application” button"},
	{Emoji: "🈴", Description: "Japanese “passing grade” button"},
	{Emoji: "🈳", Description: "Japanese “vacancy” button"},
	{Emoji: "㊗️", Description: "Japanese “congratulations” button"},
	{Emoji: "㊙️", Description: "Japanese “secret” button"},
	{Emoji: "🈺", Description: "Japanese “open for business” button"},
	{Emoji: "🈵", Description: "Japanese “no vacancy” button"},
	{Emoji: "🔴", Description: "red circle"},
	{Emoji: "🟠", Description: "orange circle"},
	{Emoji: "🟡", Description: "yellow circle"},
	{Emoji: "🟢", Description: "green circle"},
	{Emoji: "🔵", Description: "blue circle"},
	{Emoji: "🟣", Description: "purple circle"},
	{Emoji: "🟤", Description: "brown circle"},
	{Emoji: "⚫", Description: "black circle"},
	{Emoji: "⚪", Description: "white circle"},
	{Emoji: "🟥", Description: "red square"},
	{Emoji: "🟧", Description: "orange square"},
	{Emoji: "🟨", Description: "yellow square"},
	{Emoji: "🟩", Description: "green square"},
	{Emoji: "🟦", Description: "blue square"},
	{Emoji: "🟪", Description: "purple square"},
	{Emoji: "🟫", Description: "brown square"},
	{Emoji: "⬛", Description: "black large square"},
	{Emoji: "⬜", Description: "white large square"},
	{Emoji: "◼️", Description: "black medium square"},
	{Emoji: "◻️", Description: "white medium square"},
	{Emoji: "◾", Description: "black medium-small square"},
	{Emoji: "◽", Description: "white medium-small square"},
	{Emoji: "▪️", Description: "black small square"},
	{Emoji: "▫️", Description: "white small square"},
	{Emoji: "🔶", Description: "large orange diamond"},
	{Emoji: "🔷", Description: "large blue diamond"},
	{Emoji: "🔸", Description: "small orange diamond"},
	{Emoji: "🔹", Description: "small blue diamond"},
	{Emoji: "🔺", Description: "red triangle pointed up"},
	{Emoji: "🔻", Description: "red triangle pointed down"},
	{Emoji: "💠", Description: "diamond with a dot"},
	{Emoji: "🔘", Description: "radio button"},
	{Emoji: "🔳", Description: "white square button"},
	{Emoji: "🔲", Description: "black square button"},
	{Emoji: "🏁", Description: "chequered flag"},
	{Emoji: "🚩", Description: "triangular flag"},
	{Emoji: "🎌", Description: "crossed flags"},
	{Emoji: "🏴", Description: "black flag"},
	{Emoji: "🏳️", Description: "white flag"},
	{Emoji: "🏳️‍🌈", Description: "rainbow flag"},
	{Emoji: "🏳️‍⚧️", Description: "transgender flag"},
	{Emoji: "🏴‍☠️", Description: "pirate flag"},
	{Emoji: "🇦🇨", Description: "flag: Ascension Island"},
	{Emoji: "🇦🇩", Description: "flag: Andorra"},
	{Emoji: "🇦🇪", Description: "flag: United Arab Emirates"},
	{Emoji: "🇦🇫", Description: "flag: Afghanistan"},
	{Emoji: "🇦🇬", Description: "flag: Antigua & Barbuda"},
	{Emoji: "🇦🇮", Description: "flag: Anguilla"},
	{Emoji: "🇦🇱", Description: "flag: Albania"},
	{Emoji: "🇦🇲", Description: "flag: Armenia"},
	{Emoji: "🇦🇴", Description: "flag: Angola"},
	{Emoji: "🇦🇶", Description: "flag: Antarctica"},
	{Emoji: "🇦🇷", Description: "flag: Argentina"},
	{Emoji: "🇦🇸", Description: "flag: American Samoa"},
	{Emoji: "🇦🇹", Description: "flag: Austria"},
	{Emoji: "🇦🇺", Description: "flag: Australia"},
	{Emoji: "🇦🇼", Description: "flag: Aruba"},
	{Emoji: "🇦🇽", Description: "flag: Åland Islands"},
	{Emoji: "🇦🇿", Description: "flag: Azerbaijan"},
	{Emoji: "🇧🇦", Description: "flag: Bosnia & Herzegovina"},
	{Emoji: "🇧🇧", Description: "flag: Barbados"},
	{Emoji: "🇧🇩", Description: "flag: Bangladesh"},
	{Emoji: "🇧🇪", Description: "flag: Belgium"},
	{Emoji: "🇧🇫", Description: "flag: Burkina Faso"},
	{Emoji: "🇧🇬", Description: "flag: Bulgaria"},
	{Emoji: "🇧🇭", Description: "flag: Bahrain"},
	{Emoji: "🇧🇮", Description: "flag: Burundi"},
	{Emoji: "🇧🇯", Description: "flag: Benin"},
	{Emoji: "🇧🇱", Description: "flag: St. Barthélemy"},
	{Emoji: "🇧🇲", Description: "flag: Bermuda"},
	{Emoji: "🇧🇳", Description: "flag: Brunei"},
	{Emoji: "🇧🇴", Description: "flag: Bolivia"},
	{Emoji: "🇧🇶", Description: "flag: Caribbean Netherlands"},
	{Emoji: "🇧🇷", Description: "flag: Brazil"},
	{Emoji: "🇧🇸", Description: "flag: Bahamas"},
	{Emoji: "🇧🇹", Description: "flag: Bhutan"},
	{Emoji: "🇧🇻", Description: "flag: Bouvet Island"},
	{Emoji: "🇧🇼", Description: "flag: Botswana"},
	{Emoji: "🇧🇾", Description: "flag: Belarus"},
	{Emoji: "🇧🇿", Description: "flag: Belize"},
	{Emoji: "🇨🇦", Description: "flag: Canada"},
	{Emoji: "🇨🇨", Description: "flag: Cocos (Keeling) Islands"},
	{Emoji: "🇨🇩", Description: "flag: Congo - Kinshasa"},
	{Emoji: "🇨🇫", Description: "flag: Central African Republic"},
	{Emoji: "🇨🇬", Description: "flag: Congo - Brazzaville"},
	{Emoji: "🇨🇭", Description: "flag: Switzerland"},
	{Emoji: "🇨🇮", Description: "flag: Côte d’Ivoire"},
	{Emoji: "🇨🇰", Description: "flag: Cook Islands"},
	{Emoji: "🇨🇱", Description: "flag: Chile"},
	{Emoji: "🇨🇲", Description: "flag: Cameroon"},
	{Emoji: "🇨🇳", Description: "flag: China"},
	{Emoji: "🇨🇴", Description: "flag: Colombia"},
	{Emoji: "🇨🇵", Description: "flag: Clipperton Island"},
	{Emoji: "🇨🇷", Description: "flag: Costa Rica"},
	{Emoji: "🇨🇺", Description: "flag: Cuba"},
	{Emoji: "🇨🇻", Description: "flag: Cape Verde"},
	{Emoji: "🇨🇼", Description: "flag: Curaçao"},
	{Emoji: "🇨🇽", Description: "flag: Christmas Island"},
	{Emoji: "🇨🇾", Description: "flag: Cyprus"},
	{Emoji: "🇨🇿", Description: "flag: Czechia"},
	{Emoji: "🇩🇪", Description: "flag: Germany"},
	{Emoji: "🇩🇬", Description: "flag: Diego Garcia"},
	{Emoji: "🇩🇯", Description: "flag: Djibouti"},
	{Emoji: "🇩🇰", Description: "flag: Denmark"},
	{Emoji: "🇩🇲", Description: "flag: Dominica"},
	{Emoji: "🇩🇴", Description: "flag: Dominican Republic"},
	{Emoji: "🇩🇿", Description: "flag: Algeria"},
	{Emoji: "🇪🇦", Description: "flag: Ceuta & Melilla"},
	{Emoji: "🇪🇨", Description: "flag: Ecuador"},
	{Emoji: "🇪🇪", Description: "flag: Estonia"},
	{Emoji: "🇪🇬", Description: "flag: Egypt"},
	{Emoji: "🇪🇭", Description: "flag: Western Sahara"},
	{Emoji: "🇪🇷", Description: "flag: Eritrea"},
	{Emoji: "🇪🇸", Description: "flag: Spain"},
	{Emoji: "🇪🇹", Description: "flag: Ethiopia"},
	{Emoji: "🇪🇺", Description: "flag: European Union"},
	{Emoji: "🇫🇮", Description: "flag: Finland"},
	{Emoji: "🇫🇯", Description: "flag: Fiji"},
	{Emoji: "🇫🇰", Description: "flag: Falkland Islands"},
	{Emoji: "🇫🇲", Description: "flag: Micronesia"},
	{Emoji: "🇫🇴", Description: "flag: Faroe Islands"},
	{Emoji: "🇫🇷", Description: "flag: France"},
	{Emoji: "🇬🇦", Description: "flag: Gabon"},
	{Emoji: "🇬🇧", Description: "flag: United Kingdom"},
	{Emoji: "🇬🇩", Description: "flag: Grenada"},
	{Emoji: "🇬🇪", Description: "flag: Georgia"},
	{Emoji: "🇬🇫", Description: "flag: French Guiana"},
	{Emoji: "🇬🇬", Description: "flag: Guernsey"},
	{Emoji: "🇬🇭", Description: "flag: Ghana"},
	{Emoji: "🇬🇮", Description: "flag: Gibraltar"},
	{Emoji: "🇬🇱", Description: "flag: Greenland"},
	{Emoji: "🇬🇲", Description: "flag: Gambia"},
	{Emoji: "🇬🇳", Description: "flag: Guinea"},
	{Emoji: "🇬🇵", Description: "flag: Guadeloupe"},
	{Emoji: "🇬🇶", Description: "flag: Equatorial Guinea"},
	{Emoji: "🇬🇷", Description: "flag: Greece"},
	{Emoji: "🇬🇸", Description: "flag: South Georgia & South Sandwich Islands"},
	{Emoji: "🇬🇹", Description: "flag: Guatemala"},
	{Emoji: "🇬🇺", Description: "flag: Guam"},
	{Emoji: "🇬🇼", Description: "flag: Guinea-Bissau"},
	{Emoji: "🇬🇾", Description: "flag: Guyana"},
	{Emoji: "🇭🇰", Description: "flag: Hong Kong SAR China"},
	{Emoji: "🇭🇲", Description: "flag: Heard & McDonald Islands"},
	{Emoji: "🇭🇳", Description: "flag: Honduras"},
	{Emoji: "🇭🇷", Description: "flag: Croatia"},
	{Emoji: "🇭🇹", Description: "flag: Haiti"},
	{Emoji: "🇭🇺", Description: "flag: Hungary"},
	{Emoji: "🇮🇨", Description: "flag: Canary Islands"},
	{Emoji: "🇮🇩", Description: "flag: Indonesia"},
	{Emoji: "🇮🇪", Description: "flag: Ireland"},
	{Emoji: "🇮🇱", Description: "flag: Israel"},
	{Emoji: "🇮🇲", Description: "flag: Isle of Man"},
	{Emoji: "🇮🇳", Description: "flag: India"},
	{Emoji: "🇮🇴", Description: "flag: British Indian Ocean Territory"},
	{Emoji: "🇮🇶", Description: "flag: Iraq"},
	{Emoji: "🇮🇷", Description: "flag: Iran"},
	{Emoji: "🇮🇸", Description: "flag: Iceland"},
	{Emoji: "🇮🇹", Description: "flag: Italy"},
	{Emoji: "🇯🇪", Description: "flag: Jersey"},
	{Emoji: "🇯🇲", Description: "flag: Jamaica"},
	{Emoji: "🇯🇴", Description: "flag: Jordan"},
	{Emoji: "🇯🇵", Description: "flag: Japan"},
	{Emoji: "🇰🇪", Description: "flag: Kenya"},
	{Emoji: "🇰🇬", Description: "flag: Kyrgyzstan"},
	{Emoji: "🇰🇭", Description: "flag: Cambodia"},
	{Emoji: "🇰🇮", Description: "flag: Kiribati"},
	{Emoji: "🇰🇲", Description: "flag: Comoros"},
	{Emoji: "🇰🇳", Description: "flag: St. Kitts & Nevis"},
	{Emoji: "🇰🇵", Description: "flag: North Korea"},
	{Emoji: "🇰🇷", Description: "flag: South Korea"},
	{Emoji: "🇰🇼", Description: "flag: Kuwait"},
	{Emoji: "🇰🇾", Description: "flag: Cayman Islands"},
	{Emoji: "🇰🇿", Description: "flag: Kazakhstan"},
	{Emoji: "🇱🇦", Description: "flag: Laos"},
	{Emoji: "🇱🇧", Description: "flag: Lebanon"},
	{Emoji: "🇱🇨", Description: "flag: St. Lucia"},
	{Emoji: "🇱🇮", Description: "flag: Liechtenstein"},
	{Emoji: "🇱🇰", Description: "flag: Sri Lanka"},
	{Emoji: "🇱🇷", Description: "flag: Liberia"},
	{Emoji: "🇱🇸", Description: "flag: Lesotho"},
	{Emoji: "🇱🇹", Description: "flag: Lithuania"},
	{Emoji: "🇱🇺", Description: "flag: Luxembourg"},
	{Emoji: "🇱🇻", Description: "flag: Latvia"},
	{Emoji: "🇱🇾", Description: "flag: Libya"},
	{Emoji: "🇲🇦", Description: "flag: Morocco"},
	{Emoji: "🇲🇨", Description: "flag: Monaco"},
	{Emoji: "🇲🇩", Description: "flag: Moldova"},
	{Emoji: "🇲🇪", Description: "flag: Montenegro"},
	{Emoji: "🇲🇫", Description: "flag: St. Martin"},
	{Emoji: "🇲🇬", Description: "flag: Madagascar"},
	{Emoji: "🇲🇭", Description: "flag: Marshall Islands"},
	{Emoji: "🇲🇰", Description: "flag: North Macedonia"},
	{Emoji: "🇲🇱", Description: "flag: Mali"},
	{Emoji: "🇲🇲", Description: "flag: Myanmar (Burma)"},
	{Emoji: "🇲🇳", Description: "flag: Mongolia"},
	{Emoji: "🇲🇴", Description: "flag: Macao SAR China"},
	{Emoji: "🇲🇵", Description: "flag: Northern Mariana Islands"},
	{Emoji: "🇲🇶", Description: "flag: Martinique"},
	{Emoji: "🇲🇷", Description: "flag: Mauritania"},
	{Emoji: "🇲🇸", Description: "flag: Montserrat"},
	{Emoji: "🇲🇹", Description: "flag: Malta"},
	{Emoji: "🇲🇺", Description: "flag: Mauritius"},
	{Emoji: "🇲🇻", Description: "flag: Maldives"},
	{Emoji: "🇲🇼", Description: "flag: Malawi"},
	{Emoji: "🇲🇽", Description: "flag: Mexico"},
	{Emoji: "🇲🇾", Description: "flag: Malaysia"},
	{Emoji: "🇲🇿", Description: "flag: Mozambique"},
	{Emoji: "🇳🇦", Description: "flag: Namibia"},
	{Emoji: "🇳🇨", Description: "flag: New Caledonia"},
	{Emoji: "🇳🇪", Description: "flag: Niger"},
	{Emoji: "🇳🇫", Description: "flag: Norfolk Island"},
	{Emoji: "🇳🇬", Description: "flag: Nigeria"},
	{Emoji: "🇳🇮", Description: "flag: Nicaragua"},
	{Emoji: "🇳🇱", Description: "flag: Netherlands"},
	{Emoji: "🇳🇴", Description: "flag: Norway"},
	{Emoji: "🇳🇵", Description: "flag: Nepal"},
	{Emoji: "🇳🇷", Description: "flag: Nauru"},
	{Emoji: "🇳🇺", Description: "flag: Niue"},
	{Emoji: "🇳🇿", Description: "flag: New Zealand"},
	{Emoji: "🇴🇲", Description: "flag: Oman"},
	{Emoji: "🇵🇦", Description: "flag: Panama"},
	{Emoji: "🇵🇪", Description: "flag: Peru"},
	{Emoji: "🇵🇫", Description: "flag: French Polynesia"},
	{Emoji: "🇵🇬", Description: "flag: Papua New Guinea"},
	{Emoji: "🇵🇭", Description: "flag: Philippines"},
	{Emoji: "🇵🇰", Description: "flag: Pakistan"},
	{Emoji: "🇵🇱", Description: "flag: Poland"},
	{Emoji: "🇵🇲", Description: "flag: St. Pierre & Miquelon"},
	{Emoji: "🇵🇳", Description: "flag: Pitcairn Islands"},
	{Emoji: "🇵🇷", Description: "flag: Puerto Rico"},
	{Emoji: "🇵🇸", Description: "flag: Palestinian Territories"},
	{Emoji: "🇵🇹", Description: "flag: Portugal"},
	{Emoji: "🇵🇼", Description: "flag: Palau"},
	{Emoji: "🇵🇾", Description: "flag: Paraguay"},
	{Emoji: "🇶🇦", Description: "flag: Qatar"},
	{Emoji: "🇷🇪", Description: "flag: Réunion"},
	{Emoji: "🇷🇴", Description: "flag: Romania"},
	{Emoji: "🇷🇸", Description: "flag: Serbia"},
	{Emoji: "🇷🇺", Description: "flag: Russia"},
	{Emoji: "🇷🇼", Description: "flag: Rwanda"},
	{Emoji: "🇸🇦", Description: "flag: Saudi Arabia"},
	{Emoji: "🇸🇧", Description: "flag: Solomon Islands"},
	{Emoji: "🇸🇨", Description: "flag: Seychelles"},
	{Emoji: "🇸🇩", Description: "flag: Sudan"},
	{Emoji: "🇸🇪", Description: "flag: Sweden"},
	{Emoji: "🇸🇬", Description: "flag: Singapore"},
	{Emoji: "🇸🇭", Description: "flag: St. Helena"},
	{Emoji: "🇸🇮", Description: "flag: Slovenia"},
	{Emoji: "🇸🇯", Description: "flag: Svalbard & Jan Mayen"},
	{Emoji: "🇸🇰", Description: "flag: Slovakia"},
	{Emoji: "🇸🇱", Description: "flag: Sierra Leone"},
	{Emoji: "🇸🇲", Description: "flag: San Marino"},
	{Emoji: "🇸🇳", Description: "flag: Senegal"},
	{Emoji: "🇸🇴", Description: "flag: Somalia"},
	{Emoji: "🇸🇷", Description: "flag: Suriname"},
	{Emoji: "🇸🇸", Description: "flag: South Sudan"},
	{Emoji: "🇸🇹", Description: "flag: São Tomé & Príncipe"},
	{Emoji: "🇸🇻", Description: "flag: El Salvador"},
	{Emoji: "🇸🇽", Description: "flag: Sint Maarten"},
	{Emoji: "🇸🇾", Description: "flag: Syria"},
	{Emoji: "🇸🇿", Description: "flag: Eswatini"},
	{Emoji: "🇹🇦", Description: "flag: Tristan da Cunha"},
	{Emoji: "🇹🇨", Description: "flag: Turks & Caicos Islands"},
	{Emoji: "🇹🇩", Description: "flag: Chad"},
	{Emoji: "🇹🇫", Description: "flag: French Southern Territories"},
	{Emoji: "🇹🇬", Description: "flag: Togo"},
	{Emoji: "🇹🇭", Description: "flag: Thailand"},
	{Emoji: "🇹🇯", Description: "flag: Tajikistan"},
	{Emoji: "🇹🇰", Description: "flag: Tokelau"},
	{Emoji: "🇹🇱", Description: "flag: Timor-Leste"},
	{Emoji: "🇹🇲", Description: "flag: Turkmenistan"},
	{Emoji: "🇹🇳", Description: "flag: Tunisia"},
	{Emoji: "🇹🇴", Description: "flag: Tonga"},
	{Emoji: "🇹🇷", Description: "flag: Turkey"},
	{Emoji: "🇹🇹", Description: "flag: Trinidad & Tobago"},
	{Emoji: "🇹🇻", Description: "flag: Tuvalu"},
	{Emoji: "🇹🇼", Description: "flag: Taiwan"},
	{Emoji: "🇹🇿", Description: "flag: Tanzania"},
	{Emoji: "🇺🇦", Description: "flag: Ukraine"},
	{Emoji: "🇺🇬", Description: "flag: Uganda"},
	{Emoji: "🇺🇲", Description: "flag: U.S. Outlying Islands"},
	{Emoji: "🇺🇳", Description: "flag: United Nations"},
	{Emoji: "🇺🇸", Description: "flag: United States"},
	{Emoji: "🇺🇾", Description: "flag: Uruguay"},
	{Emoji: "🇺🇿", Description: "flag: Uzbekistan"},
	{Emoji: "🇻🇦", Description: "flag: Vatican City"},
	{Emoji: "🇻🇨", Description: "flag: St. Vincent & Grenadines"},
	{Emoji: "🇻🇪", Description: "flag: Venezuela"},
	{Emoji: "🇻🇬", Description: "flag: British Virgin Islands"},
	{Emoji: "🇻🇮", Description: "flag: U.S. Virgin Islands"},
	{Emoji: "🇻🇳", Description: "flag: Vietnam"},
	{Emoji: "🇻🇺", Description: "flag: Vanuatu"},
	{Emoji: "🇼🇫", Description: "flag: Wallis & Futuna"},
	{Emoji: "🇼🇸", Description: "flag: Samoa"},
	{Emoji: "🇽🇰", Description: "flag: Kosovo"},
	{Emoji: "🇾🇪", Description: "flag: Yemen"},
	{Emoji: "🇾🇹", Description: "flag: Mayotte"},
	{Emoji: "🇿🇦", Description: "flag: South Africa"},
	{Emoji: "🇿🇲", Description: "flag: Zambia"},
	{Emoji: "🇿🇼", Description: "flag: Zimbabwe"},
	{Emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", Description: "flag: England"},
	{Emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", Description: "flag: Scotland"},
	{Emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", Description: "flag: Wales"},
}
